/* Generated by           cobc 3.2.0 */
/* Generated from         glbatchUNL.cbl */
/* Generated at           Aug 31 2025 13:50:57 */
/* GnuCOBOL build date    Aug 19 2025 17:45:51 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -Wlinkage -lz -I ../copybooks -d -g -ftraceall -fdump=ALL glbatchUNL.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"glbatchUNL.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Aug 31 2025 13:50:57"
#define  COB_MODULE_DATE		20250831
#define  COB_MODULE_TIME		135057

/* Global variables */
#include "glbatchUNL.c.h"

/* Function prototypes */

static int		glbatchUNL ();
static int		glbatchUNL_ (const int);
static void		glbatchUNL_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (glbatchUNL ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'glbatchUNL' */

/* ENTRY 'glbatchUNL' */

static int
glbatchUNL ()
{
  return glbatchUNL_ (0);
}

static int
glbatchUNL_ (const int entry)
{
  /* Program local variables */
  #include "glbatchUNL.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "glbatchUNL";
  module->frame_ptr->module_stmt = 0x00100098;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 152       : Entry     glbatchUNL              : glbatchUNL.cbl */
  l_2:;
#line 152 "glbatchUNL.cbl"
  ENTRY_GLBATCHUNL:	module->statement = STMT_ENTRY;
#line 109 "glbatchUNL.c"
  module->module_stmt = 0x00100098;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 152       : Paragraph aa000-Main-Start        : glbatchUNL.cbl */
#line 152 "glbatchUNL.cbl"
  PARAGRAPH_AA000__MAIN__START_l_4:	module->statement = STMT_ENTRY;
#line 119 "glbatchUNL.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 153       : PERFORM            : glbatchUNL.cbl */
#line 153 "glbatchUNL.cbl"
  module->statement = STMT_PERFORM;
#line 126 "glbatchUNL.c"
  module->module_stmt = 0x00100099;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM zz020-Get-Program-Args */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_11;
  l_17:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 154       : MOVE               : glbatchUNL.cbl */
#line 154 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 150 "glbatchUNL.c"
  module->module_stmt = 0x0010009A;
  cob_trace_statement (STMT_MOVE);
  *(b_110 + 1092) = 50;

  /* Line: 155       : MOVE               : glbatchUNL.cbl */
#line 155 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 158 "glbatchUNL.c"
  module->module_stmt = 0x0010009B;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_110 + 1913, "13", 2);

  /* Line: 157       : MOVE               : glbatchUNL.cbl */
#line 157 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 166 "glbatchUNL.c"
  module->module_stmt = 0x0010009D;
  cob_trace_statement (STMT_MOVE);
  memset (b_103, 32, 160);

  /* Line: 158       : STRING             : glbatchUNL.cbl */
#line 158 "glbatchUNL.cbl"
  module->statement = STMT_STRING;
#line 174 "glbatchUNL.c"
  module->module_stmt = 0x0010009E;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_103, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_90);
  cob_string_append ((cob_field *)&c_1);
  cob_string_append ((cob_field *)&c_2);
  cob_string_finish ();

  /* Line: 160       : PERFORM            : glbatchUNL.cbl */
#line 160 "glbatchUNL.cbl"
  module->statement = STMT_PERFORM;
#line 187 "glbatchUNL.c"
  module->module_stmt = 0x001000A0;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_16;
  l_18:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 164       : OPEN               : glbatchUNL.cbl */
#line 164 "glbatchUNL.cbl"
  module->statement = STMT_OPEN;
#line 211 "glbatchUNL.c"
  module->module_stmt = 0x001000A4;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_BATCH_FILE, COB_OPEN_INPUT, 0, &f_113);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 165       : IF                 : glbatchUNL.cbl */
#line 165 "glbatchUNL.cbl"
  module->statement = STMT_IF;
#line 239 "glbatchUNL.c"
  module->module_stmt = 0x001000A5;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_110 + 7, 2, 0LL, 0) != 0))
  {

    /* Line: 166       : MOVE               : glbatchUNL.cbl */
#line 166 "glbatchUNL.cbl"
    module->statement = STMT_MOVE;
#line 248 "glbatchUNL.c"
    module->module_stmt = 0x001000A6;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_3, &f_103);

    /* Line: 167       : PERFORM            : glbatchUNL.cbl */
#line 167 "glbatchUNL.cbl"
    module->statement = STMT_PERFORM;
#line 256 "glbatchUNL.c"
    module->module_stmt = 0x001000A7;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM Call-Sysout */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_16;
    l_20:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;

    /* Line: 168       : CLOSE              : glbatchUNL.cbl */
#line 168 "glbatchUNL.cbl"
    module->statement = STMT_CLOSE;
#line 280 "glbatchUNL.c"
    module->module_stmt = 0x001000A8;
    cob_trace_statement (STMT_CLOSE);
    cob_close (h_BATCH_FILE, &f_113, 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_21;
      goto l_1;
      l_21:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 169       : MOVE               : glbatchUNL.cbl */
#line 169 "glbatchUNL.cbl"
    module->statement = STMT_MOVE;
#line 308 "glbatchUNL.c"
    module->module_stmt = 0x001000A9;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_4, &f_103);

    /* Line: 170       : PERFORM            : glbatchUNL.cbl */
#line 170 "glbatchUNL.cbl"
    module->statement = STMT_PERFORM;
#line 316 "glbatchUNL.c"
    module->module_stmt = 0x001000AA;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM Call-Sysout */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_16;
    l_22:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;

    /* Line: 171       : GOBACK             : glbatchUNL.cbl */
#line 171 "glbatchUNL.cbl"
    module->statement = STMT_GOBACK;
#line 340 "glbatchUNL.c"
    module->module_stmt = 0x001000AB;
    cob_trace_statement (STMT_GOBACK);
    goto exit_program;
  }

  /* Line: 173       : OPEN               : glbatchUNL.cbl */
#line 173 "glbatchUNL.cbl"
  module->statement = STMT_OPEN;
#line 349 "glbatchUNL.c"
  module->module_stmt = 0x001000AD;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_GLBATCH_FILE_SEQ, COB_OPEN_OUTPUT, 0, &f_113);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_23;
    goto l_1;
    l_23:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 174       : MOVE               : glbatchUNL.cbl */
#line 174 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 377 "glbatchUNL.c"
  module->module_stmt = 0x001000AE;
  cob_trace_statement (STMT_MOVE);
  memset (b_99 + 4, 48, 4);
  memset (b_99, 48, 4);

  /* Line: 176       : Paragraph aa010-Read-Recs         : glbatchUNL.cbl */
#line 176 "glbatchUNL.cbl"
  PARAGRAPH_AA010__READ__RECS_l_5:	module->statement = STMT_ENTRY;
#line 386 "glbatchUNL.c"
  module->module_stmt = 0x001000B0;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 177       : PERFORM            : glbatchUNL.cbl */
#line 177 "glbatchUNL.cbl"
  module->statement = STMT_PERFORM;
#line 394 "glbatchUNL.c"
  module->module_stmt = 0x001000B1;
  cob_trace_statement (STMT_PERFORM);
  for (;;)
  {

    /* Line: 178       : READ               : glbatchUNL.cbl */
#line 178 "glbatchUNL.cbl"
    module->statement = STMT_READ;
#line 403 "glbatchUNL.c"
    module->module_stmt = 0x001000B2;
    cob_trace_statement (STMT_READ);
    cob_read_next (h_BATCH_FILE, &f_113, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 179       : GO TO              : glbatchUNL.cbl */
#line 179 "glbatchUNL.cbl"
        module->statement = STMT_GO_TO;
#line 415 "glbatchUNL.c"
        module->module_stmt = 0x001000B3;
        cob_trace_statement (STMT_GO_TO);
        goto l_6;
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        frame_ptr->module_stmt = module->module_stmt;
        frame_ptr->section_name = module->section_name;
        frame_ptr->paragraph_name = module->paragraph_name;
        module->frame_ptr = frame_ptr;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_24;
        goto l_1;
        l_24:
        frame_ptr--;
        module->module_stmt = module->frame_ptr->module_stmt;
        module->section_name = module->frame_ptr->section_name;
        module->paragraph_name = module->frame_ptr->paragraph_name;
        module->frame_ptr = frame_ptr;
      }
    }

    /* Line: 181       : IF                 : glbatchUNL.cbl */
#line 181 "glbatchUNL.cbl"
    module->statement = STMT_IF;
#line 445 "glbatchUNL.c"
    module->module_stmt = 0x001000B5;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_110 + 7, 2, 0LL, 0) != 0))
    {

      /* Line: 182       : STRING             : glbatchUNL.cbl */
#line 182 "glbatchUNL.cbl"
      module->statement = STMT_STRING;
#line 454 "glbatchUNL.c"
      module->module_stmt = 0x001000B6;
      cob_trace_statement (STMT_STRING);
      cob_string_init (&f_103, NULL);
      cob_string_delimited (NULL);
      cob_string_append (&f_235);
      cob_string_append (&f_113);
      cob_string_finish ();

      /* Line: 186       : PERFORM            : glbatchUNL.cbl */
#line 186 "glbatchUNL.cbl"
      module->statement = STMT_PERFORM;
#line 466 "glbatchUNL.c"
      module->module_stmt = 0x001000BA;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM Call-Sysout */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 16;
      frame_ptr->return_address_ptr = &&l_25;
      goto l_16;
      l_25:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;

      /* Line: 187       : GO TO              : glbatchUNL.cbl */
#line 187 "glbatchUNL.cbl"
      module->statement = STMT_GO_TO;
#line 490 "glbatchUNL.c"
      module->module_stmt = 0x001000BB;
      cob_trace_statement (STMT_GO_TO);
      goto l_6;
    }

    /* Line: 189       : ADD                : glbatchUNL.cbl */
#line 189 "glbatchUNL.cbl"
    module->statement = STMT_ADD;
#line 499 "glbatchUNL.c"
    module->module_stmt = 0x001000BD;
    cob_trace_statement (STMT_ADD);
    cob_check_numeric (&f_100, "ws-Rec-Cnt-In");
    cob_add_int (&f_100, 1, 0);

    /* Line: 190       : WRITE              : glbatchUNL.cbl */
#line 190 "glbatchUNL.cbl"
    module->statement = STMT_WRITE;
#line 508 "glbatchUNL.c"
    module->module_stmt = 0x001000BE;
    cob_trace_statement (STMT_WRITE);
    memcpy (b_89, b_52, 96);
    cob_write (h_GLBATCH_FILE_SEQ, &f_53, 0, &f_113, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_26;
      goto l_1;
      l_26:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 191       : IF                 : glbatchUNL.cbl */
#line 191 "glbatchUNL.cbl"
    module->statement = STMT_IF;
#line 537 "glbatchUNL.c"
    module->module_stmt = 0x001000BF;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_110 + 7, 2, 0LL, 0) != 0))
    {

      /* Line: 192       : MOVE               : glbatchUNL.cbl */
#line 192 "glbatchUNL.cbl"
      module->statement = STMT_MOVE;
#line 546 "glbatchUNL.c"
      module->module_stmt = 0x001000C0;
      cob_trace_statement (STMT_MOVE);
      cob_move (&f_236, &f_103);

      /* Line: 193       : PERFORM            : glbatchUNL.cbl */
#line 193 "glbatchUNL.cbl"
      module->statement = STMT_PERFORM;
#line 554 "glbatchUNL.c"
      module->module_stmt = 0x001000C1;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM Call-Sysout */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 16;
      frame_ptr->return_address_ptr = &&l_27;
      goto l_16;
      l_27:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;

      /* Line: 194       : GO TO              : glbatchUNL.cbl */
#line 194 "glbatchUNL.cbl"
      module->statement = STMT_GO_TO;
#line 578 "glbatchUNL.c"
      module->module_stmt = 0x001000C2;
      cob_trace_statement (STMT_GO_TO);
      goto l_6;
    }

    /* Line: 196       : ADD                : glbatchUNL.cbl */
#line 196 "glbatchUNL.cbl"
    module->statement = STMT_ADD;
#line 587 "glbatchUNL.c"
    module->module_stmt = 0x001000C4;
    cob_trace_statement (STMT_ADD);
    cob_check_numeric (&f_101, "ws-Rec-Cnt-Out");
    cob_add_int (&f_101, 1, 0);
  }

  /* Line: 199       : Paragraph aa020-Finish-Off        : glbatchUNL.cbl */
  l_6:;
#line 199 "glbatchUNL.cbl"
  PARAGRAPH_AA020__FINISH__OFF_l_6:	module->statement = STMT_ENTRY;
#line 598 "glbatchUNL.c"
  module->module_stmt = 0x001000C7;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 200       : CLOSE              : glbatchUNL.cbl */
#line 200 "glbatchUNL.cbl"
  module->statement = STMT_CLOSE;
#line 606 "glbatchUNL.c"
  module->module_stmt = 0x001000C8;
  cob_trace_statement (STMT_CLOSE);
  cob_close (h_GLBATCH_FILE_SEQ, &f_113, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }
  cob_close (h_BATCH_FILE, &f_113, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_1;
    l_29:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 202       : MOVE               : glbatchUNL.cbl */
#line 202 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 655 "glbatchUNL.c"
  module->module_stmt = 0x001000CA;
  cob_trace_statement (STMT_MOVE);
  memset (b_103, 32, 160);

  /* Line: 203       : STRING             : glbatchUNL.cbl */
#line 203 "glbatchUNL.cbl"
  module->statement = STMT_STRING;
#line 663 "glbatchUNL.c"
  module->module_stmt = 0x001000CB;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_103, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_5);
  cob_string_append (&f_100);
  cob_string_append ((cob_field *)&c_6);
  cob_string_append (&f_101);
  cob_string_finish ();

  /* Line: 209       : PERFORM            : glbatchUNL.cbl */
#line 209 "glbatchUNL.cbl"
  module->statement = STMT_PERFORM;
#line 677 "glbatchUNL.c"
  module->module_stmt = 0x001000D1;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_30;
  goto l_16;
  l_30:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 210       : MOVE               : glbatchUNL.cbl */
#line 210 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 701 "glbatchUNL.c"
  module->module_stmt = 0x001000D2;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_4, &f_103);

  /* Line: 211       : PERFORM            : glbatchUNL.cbl */
#line 211 "glbatchUNL.cbl"
  module->statement = STMT_PERFORM;
#line 709 "glbatchUNL.c"
  module->module_stmt = 0x001000D3;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_31;
  goto l_16;
  l_31:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 212       : MOVE               : glbatchUNL.cbl */
#line 212 "glbatchUNL.cbl"
  module->statement = STMT_MOVE;
#line 733 "glbatchUNL.c"
  module->module_stmt = 0x001000D4;
  cob_trace_statement (STMT_MOVE);
  b_2 = 0;

  /* Line: 213       : GOBACK             : glbatchUNL.cbl */
#line 213 "glbatchUNL.cbl"
  module->statement = STMT_GOBACK;
#line 741 "glbatchUNL.c"
  module->module_stmt = 0x001000D5;
  cob_trace_statement (STMT_GOBACK);
  goto exit_program;

  /* Line: 17        : Section   zz010-Get-Env-Set-Files : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_7:;
#line 17 "../copybooks/Proc-Get-Env-Set-Files.cob"
  SECTION_ZZ010__GET__ENV__SET__FILES:	cob_nop ();
#line 750 "glbatchUNL.c"
  module->module_stmt = 0x00200011;
  module->section_name = st_5;
  module->paragraph_name = NULL;
  cob_trace_sect (st_5);
  cob_trace_para (NULL);

  /* Line: 20        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 20 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 760 "glbatchUNL.c"
  module->module_stmt = 0x00200014;
  cob_trace_statement (STMT_ACCEPT);
  cob_get_environment ((cob_field *)&c_7, &f_94);

  /* Line: 21        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 21 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 768 "glbatchUNL.c"
  module->module_stmt = 0x00200015;
  cob_trace_statement (STMT_ACCEPT);
  cob_get_environment ((cob_field *)&c_8, &f_93);

  /* Line: 23        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 23 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 776 "glbatchUNL.c"
  module->module_stmt = 0x00200017;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_94 + 0LL) - ' ') == 0) || 
      ((int)(int)(*(b_93 + 0LL) - ' ') == 0)))
  {

    /* Line: 25        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 25 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 786 "glbatchUNL.c"
    module->module_stmt = 0x00200019;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_239, 5120, "p", (cob_field *)&c_9);

    /* Line: 26        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 26 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 794 "glbatchUNL.c"
    module->module_stmt = 0x0020001A;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_238, 4096, "pf", (cob_field *)&c_10, (cob_field *)&c_11);

    /* Line: 27        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 27 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ACCEPT;
#line 802 "glbatchUNL.c"
    module->module_stmt = 0x0020001B;
    cob_trace_statement (STMT_ACCEPT);
    cob_accept_field (&f_102, 0, "p", (cob_field *)&c_12);

    /* Line: 28        : STOP RUN           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 28 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STOP_RUN;
#line 810 "glbatchUNL.c"
    module->module_stmt = 0x0020001C;
    cob_trace_statement (STMT_STOP_RUN);
    cob_stop_run (b_2);
  }

  /* Line: 30        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 30 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 819 "glbatchUNL.c"
  module->module_stmt = 0x0020001E;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_94 + 0LL) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_94 + 0LL) - (unsigned char)'/') == 0)))
  {

    /* Line: 31        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 31 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 829 "glbatchUNL.c"
    module->module_stmt = 0x0020001F;
    cob_trace_statement (STMT_MOVE);
    *(b_92) = *(b_94 + 0LL);
  }

  /* Line: 34        : Paragraph zz010-GESF-Exit         : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 34 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ010__GESF__EXIT_l_9:	module->statement = STMT_ENTRY;
#line 838 "glbatchUNL.c"
  module->module_stmt = 0x00200022;
  module->paragraph_name = st_6;
  cob_trace_para (st_6);

  /* Line: 35        : EXIT SECTION       : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 35 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_EXIT_SECTION;
#line 846 "glbatchUNL.c"
  module->module_stmt = 0x00200023;
  cob_trace_statement (STMT_EXIT_SECTION);
  goto l_10;

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 37        : Section   zz020-Get-Program-Args  : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_11:;
#line 37 "../copybooks/Proc-Get-Env-Set-Files.cob"
  SECTION_ZZ020__GET__PROGRAM__ARGS:	cob_nop ();
#line 862 "glbatchUNL.c"
  module->module_stmt = 0x00200025;
  module->section_name = st_7;
  module->paragraph_name = NULL;
  cob_trace_sect (st_7);
  cob_trace_para (NULL);

  /* Line: 40        : PERFORM            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 40 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_PERFORM;
#line 872 "glbatchUNL.c"
  module->module_stmt = 0x00200028;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM zz010-Get-Env-Set-Files */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_32;
  goto l_7;
  l_32:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 47        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 47 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 896 "glbatchUNL.c"
  module->module_stmt = 0x0020002F;
  cob_trace_statement (STMT_MOVE);
  memset (b_98, 32, 525);
  memset (b_226 + 27, 32, 13);

  /* Line: 49        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 49 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 905 "glbatchUNL.c"
  module->module_stmt = 0x00200031;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_13, &f_91);

  /* Line: 50        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 50 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 913 "glbatchUNL.c"
  module->module_stmt = 0x00200032;
  cob_trace_statement (STMT_ACCEPT);
  cob_accept_command_line (&f_96);

  /* Line: 51        : UNSTRING           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 51 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_UNSTRING;
#line 921 "glbatchUNL.c"
  module->module_stmt = 0x00200033;
  cob_trace_statement (STMT_UNSTRING);
  cob_unstring_init (&f_96, &f_91, 1);
  cob_unstring_delimited (&cob_all_space, 0);
  cob_unstring_into (&f_98, 0, 0);
  cob_unstring_finish ();

  /* Line: 60        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 60 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 932 "glbatchUNL.c"
  module->module_stmt = 0x0020003C;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_98 + 0LL, COB_SPACES_ALPHABETIC, 5) == 0))
  {

    /* Line: 61        : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 61 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 941 "glbatchUNL.c"
    module->module_stmt = 0x0020003D;
    cob_trace_statement (STMT_GO_TO);
    goto l_13;
  }

  /* Line: 73        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 73 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 950 "glbatchUNL.c"
  module->module_stmt = 0x00200049;
  cob_trace_statement (STMT_IF);
  if (((((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"ACAS_LEDGERS", 12) != 0) && 
      ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"NULL", 4) != 0)) && 
      ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"NONE", 4) != 0)))
  {

    /* Line: 75        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 75 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 961 "glbatchUNL.c"
    module->module_stmt = 0x0020004B;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_237, 1024, "pf", (cob_field *)&c_14, (cob_field *)&c_11);

    /* Line: 76        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 76 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 969 "glbatchUNL.c"
    module->module_stmt = 0x0020004C;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_15, 0, "pf", (cob_field *)&c_16, (cob_field *)&c_17);

    /* Line: 77        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 77 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 977 "glbatchUNL.c"
    module->module_stmt = 0x0020004D;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_95, 0, "pf", (cob_field *)&c_18, (cob_field *)&c_17);

    /* Line: 78        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 78 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 985 "glbatchUNL.c"
    module->module_stmt = 0x0020004E;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_19, 0, "pf", (cob_field *)&c_20, (cob_field *)&c_17);

    /* Line: 79        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 79 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 993 "glbatchUNL.c"
    module->module_stmt = 0x0020004F;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (COB_SET_FLD (f0, 40, b_98 + 0LL, &a_1), 0, "pf", (cob_field *)&c_21, (cob_field *)&c_17);

    /* Line: 80        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 80 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 1001 "glbatchUNL.c"
    module->module_stmt = 0x00200050;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_238, 4096, "pf", (cob_field *)&c_10, (cob_field *)&c_11);

    /* Line: 81        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 81 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ACCEPT;
#line 1009 "glbatchUNL.c"
    module->module_stmt = 0x00200051;
    cob_trace_statement (STMT_ACCEPT);
    cob_accept_field (&f_102, 0, "p", (cob_field *)&c_12);

    /* Line: 82        : STOP RUN           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 82 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STOP_RUN;
#line 1017 "glbatchUNL.c"
    module->module_stmt = 0x00200052;
    cob_trace_statement (STMT_STOP_RUN);
    cob_stop_run (b_2);
  }

  /* Line: 84        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 84 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1026 "glbatchUNL.c"
  module->module_stmt = 0x00200054;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"ACAS_LEDGERS=", 13) == 0))
  {

    /* Line: 85        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 85 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1035 "glbatchUNL.c"
    module->module_stmt = 0x00200055;
    cob_trace_statement (STMT_MOVE);
    cob_move (cob_intr_trim (0, 0, COB_SET_FLD (f0, 487, b_98 + 13LL, &a_1), 2), &f_94);
  }

  /* Line: 93        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 93 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1044 "glbatchUNL.c"
  module->module_stmt = 0x0020005D;
  cob_trace_statement (STMT_MOVE);
  memset (b_98, 32, 525);

  /* Line: 94        : UNSTRING           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 94 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_UNSTRING;
#line 1052 "glbatchUNL.c"
  module->module_stmt = 0x0020005E;
  cob_trace_statement (STMT_UNSTRING);
  cob_unstring_init (&f_96, &f_91, 1);
  cob_unstring_delimited (&cob_all_space, 0);
  cob_unstring_into (&f_98, 0, 0);
  cob_unstring_finish ();

  /* Line: 98        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 98 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1063 "glbatchUNL.c"
  module->module_stmt = 0x00200062;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_98 + 0LL, COB_SPACES_ALPHABETIC, 4) != 0))
  {

    /* Line: 103       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 103 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_IF;
#line 1072 "glbatchUNL.c"
    module->module_stmt = 0x00200067;
    cob_trace_statement (STMT_IF);
    if ((((((((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"st020", 5) == 0) || 
        ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"ST020", 5) == 0)) || 
        ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"st040", 5) == 0)) || 
        ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"ST040", 5) == 0)) || 
        ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"xl150", 5) == 0)) || 
        ((int)memcmp (b_98 + 0LL, (cob_u8_ptr)"XL150", 5) == 0)))
    {

      /* Line: 106       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 106 "../copybooks/Proc-Get-Env-Set-Files.cob"
      module->statement = STMT_MOVE;
#line 1086 "glbatchUNL.c"
      module->module_stmt = 0x0020006A;
      cob_trace_statement (STMT_MOVE);
      cob_move (cob_intr_lower_case (0, 0, COB_SET_FLD (f0, 13, b_98 + 0LL, &a_1)), &f_233);
    }
  }

  /* Line: 110       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 110 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1096 "glbatchUNL.c"
  module->module_stmt = 0x0020006E;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_94 + 0LL) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_94 + 0LL) - (unsigned char)'/') == 0)))
  {

    /* Line: 111       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 111 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1106 "glbatchUNL.c"
    module->module_stmt = 0x0020006F;
    cob_trace_statement (STMT_MOVE);
    *(b_92) = *(b_94 + 0LL);
  }

  /* Line: 118       : Paragraph zz020-Set-the-Paths     : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_13:;
#line 118 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ020__SET__THE__PATHS_l_13:	module->statement = STMT_ENTRY;
#line 1116 "glbatchUNL.c"
  module->module_stmt = 0x00200076;
  module->paragraph_name = st_8;
  cob_trace_para (st_8);

  /* Line: 119       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 119 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1124 "glbatchUNL.c"
  module->module_stmt = 0x00200077;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp (cob_intr_module_caller_id (), (cob_field *)&c_22) == 0))
  {

    /* Line: 120       : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 120 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 1133 "glbatchUNL.c"
    module->module_stmt = 0x00200078;
    cob_trace_statement (STMT_GO_TO);
    goto l_14;
  }

  /* Line: 122       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 122 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1142 "glbatchUNL.c"
  module->module_stmt = 0x0020007A;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_181 + 20750) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_181 + 20750) - (unsigned char)'/') == 0)))
  {

    /* Line: 123       : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 123 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 1152 "glbatchUNL.c"
    module->module_stmt = 0x0020007B;
    cob_trace_statement (STMT_GO_TO);
    goto l_14;
  }

  /* Line: 127       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 127 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1161 "glbatchUNL.c"
  module->module_stmt = 0x0020007F;
  cob_trace_statement (STMT_MOVE);
  (*(cob_s8_ptr) (b_91)) = 0;

  /* Line: 128       : PERFORM            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 128 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_PERFORM;
#line 1169 "glbatchUNL.c"
  module->module_stmt = 0x00200080;
  cob_trace_statement (STMT_PERFORM);
  for (n0 = (*(short *)(b_181 + 20748)); n0 > 0; n0--)
  {

    /* Line: 129       : ADD                : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 129 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ADD;
#line 1178 "glbatchUNL.c"
    module->module_stmt = 0x00200081;
    cob_trace_statement (STMT_ADD);
    cob_add_s8 (b_91, 1);

    /* Line: 130       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 130 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1186 "glbatchUNL.c"
    module->module_stmt = 0x00200082;
    cob_trace_statement (STMT_MOVE);
    memset (b_98, 32, 525);

    /* Line: 131       : STRING             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 131 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STRING;
#line 1194 "glbatchUNL.c"
    module->module_stmt = 0x00200083;
    cob_trace_statement (STMT_STRING);
    cob_string_init (&f_98, NULL);
    cob_string_delimited (&cob_all_space);
    cob_string_append (&f_94);
    cob_string_delimited (NULL);
    cob_string_append (&f_92);
    cob_string_delimited (&cob_all_space);
    cob_string_append (
    (cob_check_subscript ((*(cob_s8_ptr) (b_91)), 39, "System-File-Names", 0),
    COB_SET_FLD (f0, 532, b_181 + 532LL * ((cob_s64_t)((*(cob_s8_ptr) (b_91))) - 1), &a_1) ));
    cob_string_finish ();

    /* Line: 136       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 136 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1211 "glbatchUNL.c"
    module->module_stmt = 0x00200088;
    cob_trace_statement (STMT_MOVE);
    cob_check_subscript ((*(cob_s8_ptr) (b_91)), 39, "System-File-Names", 0);
    cob_move (&f_98, COB_SET_FLD (f0, 532, b_181 + 532LL * ((cob_s64_t)((*(cob_s8_ptr) (b_91))) - 1), &a_1));
  }

  /* Line: 138       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 138 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1221 "glbatchUNL.c"
  module->module_stmt = 0x0020008A;
  cob_trace_statement (STMT_MOVE);
  (*(cob_s8_ptr) (b_91)) = 0;

  /* Line: 139       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 139 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1229 "glbatchUNL.c"
  module->module_stmt = 0x0020008B;
  cob_trace_statement (STMT_MOVE);
  *(b_181 + 20750) = *(b_92);

  /* Line: 141       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 141 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1237 "glbatchUNL.c"
  module->module_stmt = 0x0020008D;
  cob_trace_statement (STMT_MOVE);
  memset (b_110 + 18, 32, 525);

  /* Line: 142       : STRING             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 142 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_STRING;
#line 1245 "glbatchUNL.c"
  module->module_stmt = 0x0020008E;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_123, NULL);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_94);
  cob_string_delimited (NULL);
  cob_string_append (&f_92);
  cob_string_finish ();

  /* Line: 146       : Paragraph zz020-Exit              : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_14:;
#line 146 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ020__EXIT_l_14:	module->statement = STMT_ENTRY;
#line 1259 "glbatchUNL.c"
  module->module_stmt = 0x00200092;
  module->paragraph_name = st_9;
  cob_trace_para (st_9);

  /* Line: 147       : EXIT SECTION       : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 147 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_EXIT_SECTION;
#line 1267 "glbatchUNL.c"
  module->module_stmt = 0x00200093;
  cob_trace_statement (STMT_EXIT_SECTION);
  goto l_15;

  /* Line: 217       : Paragraph Call-Sysout             : glbatchUNL.cbl */
  l_16:;
#line 217 "glbatchUNL.cbl"
  PARAGRAPH_CALL__SYSOUT_l_16:	module->statement = STMT_ENTRY;
#line 1276 "glbatchUNL.c"
  module->module_stmt = 0x001000D9;
  module->paragraph_name = st_10;
  cob_trace_para (st_10);

  /* Line: 218       : CALL               : glbatchUNL.cbl */
#line 218 "glbatchUNL.cbl"
  module->statement = STMT_CALL;
#line 1284 "glbatchUNL.c"
  module->module_stmt = 0x001000DA;
  cob_trace_statement (STMT_CALL);
  cob_procedure_params[0] = &f_103;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
  if (memcmp (b_103_fence_pre, "\x00\x00\x00\x00\x00\x00\x00", 8) == 0) {
    memcpy (b_103_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
    memcpy (b_103_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);
  } else {
    cob_check_fence (b_103_fence_pre, b_103_fence_post, STMT_BEFORE_CALL, "SO-Print");
  }
    if (unlikely(call_ACAS__Sysout.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_ACAS__Sysout.funcvoid = cob_resolve_cobol ("ACAS-Sysout", 0, 1);
  }
  b_2 = ((int (*)(void *))call_ACAS__Sysout.funcint) (b_103);
  cob_check_fence (b_103_fence_pre, b_103_fence_post, STMT_CALL, "SO-Print");
  cob_check_fence (call_fence_pre, call_fence_post, STMT_CALL, NULL);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Implicit EXIT label */
  l_15:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 220       : last source line                  :glbatchUNL.cbl */
#line 220 "glbatchUNL.cbl"
  module->module_stmt = 0x001000DC;
#line 1319 "glbatchUNL.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : glbatchUNL.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  glbatchUNL_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = &f_240;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize call-pointer memory fence */
  memcpy (call_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
  memcpy (call_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field prog-name */
#line 117 "glbatchUNL.cbl"
  cob_nop ();
#line 1395 "glbatchUNL.c"
  memcpy (b_90, "glbatchUNL (3.02.00)", 20);

  /* initialize field z */
#line 118 "glbatchUNL.cbl"
  cob_nop ();
#line 1401 "glbatchUNL.c"
  (*(cob_s8_ptr) (b_91)) = 0;

  /* initialize field OS-Delimiter */
#line 119 "glbatchUNL.cbl"
  cob_nop ();
#line 1407 "glbatchUNL.c"
  *(cob_u8_ptr)(b_92) = (unsigned char)'/';

  /* initialize field ACAS_BIN */
#line 120 "glbatchUNL.cbl"
  cob_nop ();
#line 1413 "glbatchUNL.c"
  memset (b_93, 32, 512);

  /* initialize field ACAS_LEDGERS */
#line 121 "glbatchUNL.cbl"
  cob_nop ();
#line 1419 "glbatchUNL.c"
  memset (b_94, 32, 500);

  /* initialize field Arg-Number */
#line 122 "glbatchUNL.cbl"
  cob_nop ();
#line 1425 "glbatchUNL.c"
  *(cob_u8_ptr)(b_95) = 48;

  /* initialize field Arg-Vals */
#line 125 "glbatchUNL.cbl"
  cob_nop ();
#line 1431 "glbatchUNL.c"
  memset (b_96, 32, 1050);

  /* initialize field Arg-Test */
#line 127 "glbatchUNL.cbl"
  cob_nop ();
#line 1437 "glbatchUNL.c"
  memset (b_98, 32, 525);

  /* initialize field ws-Rec-Cnt-In */
#line 130 "glbatchUNL.cbl"
  cob_nop ();
#line 1443 "glbatchUNL.c"
  memset (b_99, 48, 4);
  /* initialize field ws-Rec-Cnt-Out */
#line 131 "glbatchUNL.cbl"
  cob_nop ();
#line 1448 "glbatchUNL.c"
  memset (b_99 + 4, 48, 4);
  /* initialize field ws-reply */
#line 132 "glbatchUNL.cbl"
  cob_nop ();
#line 1453 "glbatchUNL.c"
  *(cob_u8_ptr)(b_99 + 8) = (unsigned char)' ';

  /* initialize field SO-Print */
#line 134 "glbatchUNL.cbl"
  cob_nop ();
#line 1459 "glbatchUNL.c"
  memset (b_103, 32, 160);

  /* initialize field SW-Testing */
#line 10 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1465 "glbatchUNL.c"
  *(b_104) = 49;
  /* initialize field SW-Testing-2 */
#line 15 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1470 "glbatchUNL.c"
  *(cob_u8_ptr)(b_104 + 1) = 48;
  /* initialize field Log-File-Rec-Written */
#line 18 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1475 "glbatchUNL.c"
  memset (b_104 + 2, 48, 6);

  /* initialize field We-Error */
#line 23 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1481 "glbatchUNL.c"
  memset (b_110, (unsigned char)'0', 3);
  /* initialize field Rrn */
#line 24 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1486 "glbatchUNL.c"
  memset (b_110 + 3, 0x0, 4);
  /* initialize field fs-reply */
#line 25 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1491 "glbatchUNL.c"
  memset (b_110 + 7, (unsigned char)'0', 2);
  /* initialize field s1 */
#line 26 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1496 "glbatchUNL.c"
  *(cob_u8_ptr)(b_110 + 9) = (unsigned char)' ';
  /* initialize field Curs */
#line 27 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1501 "glbatchUNL.c"
  memset (b_110 + 10, (unsigned char)'0', 8);
  /* initialize field ACAS-Path */
#line 38 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1506 "glbatchUNL.c"
  memset (b_110 + 18, 32, 525);
  /* initialize field Path-Work */
#line 39 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1511 "glbatchUNL.c"
  memset (b_110 + 543, 32, 525);
  /* initialize field FS-Action */
#line 41 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1516 "glbatchUNL.c"
  memset (b_110 + 1068, 32, 22);
  /* initialize field Accept-Reply */
#line 45 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1521 "glbatchUNL.c"
  *(cob_u8_ptr)(b_110 + 1090) = 32;
  /* initialize field File-Key-No */
#line 46 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1526 "glbatchUNL.c"
  *(cob_u8_ptr)(b_110 + 1091) = (unsigned char)'0';
  /* initialize field ws-Log-System */
#line 47 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1531 "glbatchUNL.c"
  *(cob_u8_ptr)(b_110 + 1092) = 48;
  /* initialize field ws-No-Paragraph */
#line 48 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1536 "glbatchUNL.c"
  memset (b_110 + 1093, (unsigned char)'0', 3);
  /* initialize field SQL-Err */
#line 49 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1541 "glbatchUNL.c"
  memset (b_110 + 1096, (unsigned char)' ', 5);
  /* initialize field SQL-Msg */
#line 50 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1546 "glbatchUNL.c"
  memset (b_110 + 1101, 32, 512);
  /* initialize field SQL-State */
#line 51 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1551 "glbatchUNL.c"
  memset (b_110 + 1613, (unsigned char)' ', 5);
  /* initialize field WS-File-Key */
#line 52 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1556 "glbatchUNL.c"
  memset (b_110 + 1618, 32, 64);
  /* initialize field WS-Log-Where */
#line 53 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1561 "glbatchUNL.c"
  memset (b_110 + 1682, 32, 231);
  /* initialize field WS-Log-File-No */
#line 54 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1566 "glbatchUNL.c"
  memset (b_110 + 1913, 48, 2);
  /* initialize field WS-Count-Rows */
#line 55 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1571 "glbatchUNL.c"
  memset (b_110 + 1915, 48, 7);
  /* initialize field DB-Schema */
#line 57 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1576 "glbatchUNL.c"
  memset (b_110 + 1922, 32, 12);
  /* initialize field DB-UName */
#line 58 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1581 "glbatchUNL.c"
  memset (b_110 + 1934, 32, 12);
  /* initialize field DB-UPass */
#line 59 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1586 "glbatchUNL.c"
  memset (b_110 + 1946, 32, 12);
  /* initialize field DB-Host */
#line 60 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1591 "glbatchUNL.c"
  memset (b_110 + 1958, 32, 32);
  /* initialize field DB-Socket */
#line 61 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1596 "glbatchUNL.c"
  memset (b_110 + 1990, 32, 64);
  /* initialize field DB-Port */
#line 62 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1601 "glbatchUNL.c"
  memset (b_110 + 2054, 32, 5);
  /* initialize field Main-Record-Move-Flag */
#line 66 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1606 "glbatchUNL.c"
  *(cob_u8_ptr)(b_110 + 2059) = 48;
  /* initialize field FA-RDBMS-Flat-Statuses */
#line 72 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1611 "glbatchUNL.c"
  memset (b_110 + 2060, (unsigned char)'0', 5);

  /* initialize field pre-trans-name */
#line 13 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1617 "glbatchUNL.c"
  memcpy (b_181, "pretrans.tmp", 12);
  memset (b_181 + 12, ' ', 520);
  /* initialize field post-trans-name */
#line 14 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1623 "glbatchUNL.c"
  memcpy (b_181 + 532, "postrans.tmp", 12);
  memset (b_181 + 532 + 12, ' ', 520);
  /* initialize field file-0 */
#line 1 "../copybooks/file00.cob"
  cob_nop ();
#line 1629 "glbatchUNL.c"
  memcpy (b_181 + 1064, "system.dat", 10);
  memset (b_181 + 1064 + 10, ' ', 522);
  /* initialize field file-2 */
#line 1 "../copybooks/file02.cob"
  cob_nop ();
#line 1635 "glbatchUNL.c"
  memcpy (b_181 + 1596, "archive.dat", 11);
  memset (b_181 + 1596 + 11, ' ', 521);
  /* initialize field file-3 */
#line 1 "../copybooks/file03.cob"
  cob_nop ();
#line 1641 "glbatchUNL.c"
  memcpy (b_181 + 2128, "final.dat", 9);
  memset (b_181 + 2128 + 9, ' ', 523);
  /* initialize field file-4 */
#line 1 "../copybooks/file04.cob"
  cob_nop ();
#line 1647 "glbatchUNL.c"
  memcpy (b_181 + 2660, "slautogen.dat", 13);
  memset (b_181 + 2660 + 13, ' ', 519);
  /* initialize field file-5 */
#line 1 "../copybooks/file05.cob"
  cob_nop ();
#line 1653 "glbatchUNL.c"
  memcpy (b_181 + 3192, "ledger.dat", 10);
  memset (b_181 + 3192 + 10, ' ', 522);
  /* initialize field file-6 */
#line 1 "../copybooks/file06.cob"
  cob_nop ();
#line 1659 "glbatchUNL.c"
  memcpy (b_181 + 3724, "posting.dat", 11);
  memset (b_181 + 3724 + 11, ' ', 521);
  /* initialize field file-7 */
#line 1 "../copybooks/file07.cob"
  cob_nop ();
#line 1665 "glbatchUNL.c"
  memcpy (b_181 + 4256, "batch.dat", 9);
  memset (b_181 + 4256 + 9, ' ', 523);
  /* initialize field file-8 */
#line 1 "../copybooks/file08.cob"
  cob_nop ();
#line 1671 "glbatchUNL.c"
  memcpy (b_181 + 4788, "postings2irs.dat", 16);
  memset (b_181 + 4788 + 16, ' ', 516);
  /* initialize field file-9 */
#line 1 "../copybooks/file09.cob"
  cob_nop ();
#line 1677 "glbatchUNL.c"
  memcpy (b_181 + 5320, "tmp-stock.dat", 13);
  memset (b_181 + 5320 + 13, ' ', 519);
  /* initialize field file-10 */
#line 1 "../copybooks/file10.cob"
  cob_nop ();
#line 1683 "glbatchUNL.c"
  memcpy (b_181 + 5852, "staudit.dat", 11);
  memset (b_181 + 5852 + 11, ' ', 521);
  /* initialize field file-11 */
#line 1 "../copybooks/file11.cob"
  cob_nop ();
#line 1689 "glbatchUNL.c"
  memcpy (b_181 + 6384, "stockctl.dat", 12);
  memset (b_181 + 6384 + 12, ' ', 520);
  /* initialize field file-12 */
#line 1 "../copybooks/file12.cob"
  cob_nop ();
#line 1695 "glbatchUNL.c"
  memcpy (b_181 + 6916, "salesled.dat", 12);
  memset (b_181 + 6916 + 12, ' ', 520);
  /* initialize field file-13 */
#line 1 "../copybooks/file13.cob"
  cob_nop ();
#line 1701 "glbatchUNL.c"
  memcpy (b_181 + 7448, "value.dat", 9);
  memset (b_181 + 7448 + 9, ' ', 523);
  /* initialize field file-14 */
#line 1 "../copybooks/file14.cob"
  cob_nop ();
#line 1707 "glbatchUNL.c"
  memcpy (b_181 + 7980, "delivery.dat", 12);
  memset (b_181 + 7980 + 12, ' ', 520);
  /* initialize field file-15 */
#line 1 "../copybooks/file15.cob"
  cob_nop ();
#line 1713 "glbatchUNL.c"
  memcpy (b_181 + 8512, "analysis.dat", 12);
  memset (b_181 + 8512 + 12, ' ', 520);
  /* initialize field file-16 */
#line 1 "../copybooks/file16.cob"
  cob_nop ();
#line 1719 "glbatchUNL.c"
  memcpy (b_181 + 9044, "invoice.dat", 11);
  memset (b_181 + 9044 + 11, ' ', 521);
  /* initialize field file-17 */
#line 1 "../copybooks/file17.cob"
  cob_nop ();
#line 1725 "glbatchUNL.c"
  memcpy (b_181 + 9576, "delinvno.dat", 12);
  memset (b_181 + 9576 + 12, ' ', 520);
  /* initialize field file-18 */
#line 1 "../copybooks/file18.cob"
  cob_nop ();
#line 1731 "glbatchUNL.c"
  memcpy (b_181 + 10108, "openitm2.dat", 12);
  memset (b_181 + 10108 + 12, ' ', 520);
  /* initialize field file-19 */
#line 1 "../copybooks/file19.cob"
  cob_nop ();
#line 1737 "glbatchUNL.c"
  memcpy (b_181 + 10640, "openitm3.dat", 12);
  memset (b_181 + 10640 + 12, ' ', 520);
  /* initialize field file-20 */
#line 1 "../copybooks/file20.cob"
  cob_nop ();
#line 1743 "glbatchUNL.c"
  memcpy (b_181 + 11172, "oisort.wrk", 10);
  memset (b_181 + 11172 + 10, ' ', 522);
  /* initialize field file-21 */
#line 1 "../copybooks/file21.cob"
  cob_nop ();
#line 1749 "glbatchUNL.c"
  memcpy (b_181 + 11704, "work.tmp", 8);
  memset (b_181 + 11704 + 8, ' ', 524);
  /* initialize field file-22 */
#line 1 "../copybooks/file22.cob"
  cob_nop ();
#line 1755 "glbatchUNL.c"
  memcpy (b_181 + 12236, "purchled.dat", 12);
  memset (b_181 + 12236 + 12, ' ', 520);
  /* initialize field file-23 */
#line 1 "../copybooks/file23.cob"
  cob_nop ();
#line 1761 "glbatchUNL.c"
  memcpy (b_181 + 12768, "delfolio.dat", 12);
  memset (b_181 + 12768 + 12, ' ', 520);
  /* initialize field file-24 */
#line 1 "../copybooks/file24.cob"
  cob_nop ();
#line 1767 "glbatchUNL.c"
  memset (b_181 + 13300, 32, 532);
  /* initialize field file-26 */
#line 1 "../copybooks/file26.cob"
  cob_nop ();
#line 1772 "glbatchUNL.c"
  memcpy (b_181 + 13832, "pinvoice.dat", 12);
  memset (b_181 + 13832 + 12, ' ', 520);
  /* initialize field file-27 */
#line 1 "../copybooks/file27.cob"
  cob_nop ();
#line 1778 "glbatchUNL.c"
  memcpy (b_181 + 14364, "poisort.wrk", 11);
  memset (b_181 + 14364 + 11, ' ', 521);
  /* initialize field file-28 */
#line 1 "../copybooks/file28.cob"
  cob_nop ();
#line 1784 "glbatchUNL.c"
  memcpy (b_181 + 14896, "openitm4.dat", 12);
  memset (b_181 + 14896 + 12, ' ', 520);
  /* initialize field file-29 */
#line 1 "../copybooks/file29.cob"
  cob_nop ();
#line 1790 "glbatchUNL.c"
  memcpy (b_181 + 15428, "openitm5.dat", 12);
  memset (b_181 + 15428 + 12, ' ', 520);
  /* initialize field file-30 */
#line 1 "../copybooks/file30.cob"
  cob_nop ();
#line 1796 "glbatchUNL.c"
  memcpy (b_181 + 15960, "plautogen.dat", 13);
  memset (b_181 + 15960 + 13, ' ', 519);
  /* initialize field file-31 */
#line 1 "../copybooks/file31.cob"
  cob_nop ();
#line 1802 "glbatchUNL.c"
  memcpy (b_181 + 16492, "bostkitm.dat", 12);
  memset (b_181 + 16492 + 12, ' ', 520);
  /* initialize field file-32 */
#line 1 "../copybooks/file32.cob"
  cob_nop ();
#line 1808 "glbatchUNL.c"
  memcpy (b_181 + 17024, "pay.dat", 7);
  memset (b_181 + 17024 + 7, ' ', 525);
  /* initialize field file-33 */
#line 1 "../copybooks/file33.cob"
  cob_nop ();
#line 1814 "glbatchUNL.c"
  memcpy (b_181 + 17556, "cheque.dat", 10);
  memset (b_181 + 17556 + 10, ' ', 522);
  /* initialize field file-34 */
#line 48 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1820 "glbatchUNL.c"
  memcpy (b_181 + 18088, "irsacnts.dat", 12);
  memset (b_181 + 18088 + 12, ' ', 520);
  /* initialize field file-35 */
#line 49 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1826 "glbatchUNL.c"
  memcpy (b_181 + 18620, "irsdflt.dat", 11);
  memset (b_181 + 18620 + 11, ' ', 521);
  /* initialize field file-36 */
#line 50 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1832 "glbatchUNL.c"
  memcpy (b_181 + 19152, "irspost.dat", 11);
  memset (b_181 + 19152 + 11, ' ', 521);
  /* initialize field file-37 */
#line 51 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1838 "glbatchUNL.c"
  memcpy (b_181 + 19684, "irsfinal.dat", 12);
  memset (b_181 + 19684 + 12, ' ', 520);
  /* initialize field file-38 */
#line 52 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1844 "glbatchUNL.c"
  memcpy (b_181 + 20216, "postsort.dat", 12);
  memset (b_181 + 20216 + 12, ' ', 520);
  /* initialize field File-Defs-Count */
#line 55 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1850 "glbatchUNL.c"
  cob_move ((cob_field *)&c_23, &f_224);
  /* initialize field File-Defs-os-Delimiter */
#line 56 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1855 "glbatchUNL.c"
  *(cob_u8_ptr)(b_181 + 20750) = (unsigned char)' ';

  /* initialize field WS-Called */
#line 6 "../copybooks/wscall.cob"
  cob_nop ();
#line 1861 "glbatchUNL.c"
  memset (b_226, (unsigned char)' ', 24);
  /* initialize field WS-Term-Code */
#line 9 "../copybooks/wscall.cob"
  cob_nop ();
#line 1866 "glbatchUNL.c"
  memset (b_226 + 24, (unsigned char)'0', 3);
  /* initialize field WS-CD-Args */
#line 13 "../copybooks/wscall.cob"
  cob_nop ();
#line 1871 "glbatchUNL.c"
  memset (b_226 + 27, (unsigned char)' ', 13);

  /* initialize field SY003 */
#line 143 "glbatchUNL.cbl"
  cob_nop ();
#line 1877 "glbatchUNL.c"
  memcpy (b_234, "SY003 Problem reading batch file = ", 35);
  /* initialize field SY006 */
#line 144 "glbatchUNL.cbl"
  cob_nop ();
#line 1882 "glbatchUNL.c"
  memcpy (b_234 + 35, "SYS06 Write error on .seq file", 30);
  /* initialize field SY007 */
#line 145 "glbatchUNL.cbl"
  cob_nop ();
#line 1887 "glbatchUNL.c"
  memcpy (b_234 + 65, "SY007 Program arguments incorrect: ", 35);
  /* initialize field SY008 */
#line 146 "glbatchUNL.cbl"
  cob_nop ();
#line 1892 "glbatchUNL.c"
  memcpy (b_234 + 100, "SY008 Note message & Hit return", 31);
  /* initialize field SY009 */
#line 147 "glbatchUNL.cbl"
  cob_nop ();
#line 1897 "glbatchUNL.c"
  memcpy (b_234 + 131, "SY009 Environment variables not yet set up : ABORTING", 53);

  /* initialize field COB-CRT-STATUS */
#line 149 "glbatchUNL.cbl"
  cob_nop ();
#line 1903 "glbatchUNL.c"
  memset (b_240, (unsigned char)'0', 4);


  /* File initialization for batch-file */
  cob_file_malloc (&h_BATCH_FILE, &k_BATCH_FILE, 1, 0);
  k_BATCH_FILE->field = &f_18;
  k_BATCH_FILE->tf_duplicates = 0;
  k_BATCH_FILE->offset = 0;
  h_BATCH_FILE->select_name = (const char *)"batch-file";
  h_BATCH_FILE->file_status = h_BATCH_FILE_status;
  memset (h_BATCH_FILE_status, '0', 2);
  h_BATCH_FILE->assign = &f_191;
  h_BATCH_FILE->record = &f_52;
  h_BATCH_FILE->variable_record = NULL;
  h_BATCH_FILE->record_min = 96;
  h_BATCH_FILE->record_max = 96;
  h_BATCH_FILE->file = NULL;
  h_BATCH_FILE->organization = 3;
  h_BATCH_FILE->access_mode = 2;
  h_BATCH_FILE->lock_mode = 0;
  h_BATCH_FILE->open_mode = 0;
  h_BATCH_FILE->flag_optional = 0;
  h_BATCH_FILE->flag_line_adv = 0;
  h_BATCH_FILE->flag_select_features = 1;

  /* File initialization for glbatch-File-Seq */
  cob_file_malloc (&h_GLBATCH_FILE_SEQ, NULL, 0, 0);
  h_GLBATCH_FILE_SEQ->select_name = (const char *)"glbatch-File-Seq";
  h_GLBATCH_FILE_SEQ->file_status = h_GLBATCH_FILE_SEQ_status;
  memset (h_GLBATCH_FILE_SEQ_status, '0', 2);
  h_GLBATCH_FILE_SEQ->assign = (cob_field *)&c_24;
  h_GLBATCH_FILE_SEQ->record = &f_89;
  h_GLBATCH_FILE_SEQ->variable_record = NULL;
  h_GLBATCH_FILE_SEQ->record_min = 96;
  h_GLBATCH_FILE_SEQ->record_max = 96;
  h_GLBATCH_FILE_SEQ->file = NULL;
  h_GLBATCH_FILE_SEQ->organization = 0;
  h_GLBATCH_FILE_SEQ->access_mode = 1;
  h_GLBATCH_FILE_SEQ->lock_mode = 0;
  h_GLBATCH_FILE_SEQ->open_mode = 0;
  h_GLBATCH_FILE_SEQ->flag_optional = 0;
  h_GLBATCH_FILE_SEQ->flag_line_adv = 0;
  h_GLBATCH_FILE_SEQ->flag_select_features = 1;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump batch-file */
  cob_dump_file ("FD batch-file", h_BATCH_FILE);
  cob_dump_field_ext ( 1, "Batch-Record", &f_17, 0, 0);
  cob_dump_field_ext ( 3, "batch-key", &f_18, 0, 0);
  cob_dump_field_ext ( 5, "Ledger", COB_SET_FLD (f0, 1, b_17, &a_9), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Nos", COB_SET_FLD (f0, 5, b_17 + 1, &a_12), 0, 0);
  cob_dump_field_ext ( 3, "Items", COB_SET_FLD (f0, 2, b_17 + 6, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Batch-Status", COB_SET_FLD (f0, 1, b_17 + 8, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Cleared-Status", COB_SET_FLD (f0, 1, b_17 + 9, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Bcycle", COB_SET_FLD (f0, 2, b_17 + 10, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Dates", COB_SET_FLD (f0, 16, b_17 + 12, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Entered", COB_SET_FLD (f0, 4, b_17 + 12, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Proofed", COB_SET_FLD (f0, 4, b_17 + 16, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Posted", COB_SET_FLD (f0, 4, b_17 + 20, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Stored", COB_SET_FLD (f0, 4, b_17 + 24, &a_13), 0, 0);
  cob_dump_field_ext ( 3, "Amounts", COB_SET_FLD (f0, 24, b_17 + 28, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Input-Gross", COB_SET_FLD (f0, 6, b_17 + 28, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Input-Vat", COB_SET_FLD (f0, 6, b_17 + 34, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Actual-Gross", COB_SET_FLD (f0, 6, b_17 + 40, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Actual-Vat", COB_SET_FLD (f0, 6, b_17 + 46, &a_14), 0, 0);
  cob_dump_field_ext ( 3, "Description", COB_SET_FLD (f0, 24, b_17 + 52, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "posting-data", COB_SET_FLD (f0, 15, b_17 + 76, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "bDefault", COB_SET_FLD (f0, 2, b_17 + 76, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "Convention", COB_SET_FLD (f0, 2, b_17 + 78, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-AC", COB_SET_FLD (f0, 6, b_17 + 80, &a_15), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-PC", COB_SET_FLD (f0, 2, b_17 + 86, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-Code", COB_SET_FLD (f0, 2, b_17 + 88, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-Vat", COB_SET_FLD (f0, 1, b_17 + 90, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Batch-Start", COB_SET_FLD (f0, 5, b_17 + 91, &a_12), 0, 0);

  /* Dump glbatch-File-Seq */
  cob_dump_file ("FD glbatch-File-Seq", h_GLBATCH_FILE_SEQ);
  cob_dump_field_ext ( 1, "WS-Batch-Record", &f_53, 0, 0);
  cob_dump_field_ext ( 3, "WS-Batch-Key", COB_SET_FLD (f0, 6, b_53, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "WS-Ledger", COB_SET_FLD (f0, 1, b_53, &a_9), 0, 0);
  cob_dump_field_ext ( 5, "WS-Batch-Nos", COB_SET_FLD (f0, 5, b_53 + 1, &a_12), 0, 0);
  cob_dump_field_ext ( 3, "Items", COB_SET_FLD (f0, 2, b_53 + 6, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Batch-Status", COB_SET_FLD (f0, 1, b_53 + 8, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Cleared-Status", COB_SET_FLD (f0, 1, b_53 + 9, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Bcycle", COB_SET_FLD (f0, 2, b_53 + 10, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Dates", COB_SET_FLD (f0, 16, b_53 + 12, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Entered", COB_SET_FLD (f0, 4, b_53 + 12, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Proofed", COB_SET_FLD (f0, 4, b_53 + 16, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Posted", COB_SET_FLD (f0, 4, b_53 + 20, &a_13), 0, 0);
  cob_dump_field_ext ( 5, "Stored", COB_SET_FLD (f0, 4, b_53 + 24, &a_13), 0, 0);
  cob_dump_field_ext ( 3, "Amounts", COB_SET_FLD (f0, 24, b_53 + 28, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Input-Gross", COB_SET_FLD (f0, 6, b_53 + 28, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Input-Vat", COB_SET_FLD (f0, 6, b_53 + 34, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Actual-Gross", COB_SET_FLD (f0, 6, b_53 + 40, &a_14), 0, 0);
  cob_dump_field_ext ( 5, "Actual-Vat", COB_SET_FLD (f0, 6, b_53 + 46, &a_14), 0, 0);
  cob_dump_field_ext ( 3, "Description", COB_SET_FLD (f0, 24, b_53 + 52, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "posting-data", COB_SET_FLD (f0, 15, b_53 + 76, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "bDefault", COB_SET_FLD (f0, 2, b_53 + 76, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "Convention", COB_SET_FLD (f0, 2, b_53 + 78, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-AC", COB_SET_FLD (f0, 6, b_53 + 80, &a_15), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-PC", COB_SET_FLD (f0, 2, b_53 + 86, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-Code", COB_SET_FLD (f0, 2, b_53 + 88, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "Batch-Def-Vat", COB_SET_FLD (f0, 1, b_53 + 90, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Batch-Start", COB_SET_FLD (f0, 5, b_53 + 91, &a_12), 0, 0);

  /* Dump WORKING-STORAGE */
  cob_dump_output ("WORKING-STORAGE");
  cob_dump_field_ext (77, "RETURN-CODE", &f_2, 0, 0);
  cob_dump_field_ext (77, "prog-name", &f_90, 0, 0);
  cob_dump_field_ext (77, "z", &f_91, 0, 0);
  cob_dump_field_ext (77, "OS-Delimiter", &f_92, 0, 0);
  cob_dump_field_ext (77, "ACAS_BIN", &f_93, 0, 0);
  cob_dump_field_ext (77, "ACAS_LEDGERS", &f_94, 0, 0);
  cob_dump_field_ext (77, "Arg-Number", &f_95, 0, 0);
  cob_dump_field_ext ( 1, "Arg-Vals", &f_96, 0, 0);
  {
    int i_1;
    int max_1 = 2;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 3, "Arg-Value", COB_SET_FLD (f0, 525, b_96, &a_1), 0, 1, i_1, 525UL);
    }
  }
  cob_dump_field_ext ( 1, "Arg-Test", &f_98, 0, 0);
  cob_dump_field_ext ( 1, "work-fields", COB_SET_FLD (f0, 9, b_99, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "ws-Rec-Cnt-In", &f_100, 0, 0);
  cob_dump_field_ext ( 3, "ws-Rec-Cnt-Out", &f_101, 0, 0);
  cob_dump_field_ext ( 3, "ws-reply", &f_102, 0, 0);
  cob_dump_field_ext ( 1, "SO-Print", &f_103, 0, 0);
  cob_dump_field_ext ( 1, "ACAS-DAL-Common-data", COB_SET_FLD (f0, 8, b_104, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "SW-Testing", COB_SET_FLD (f0, 1, b_104, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "SW-Testing-2", COB_SET_FLD (f0, 1, b_104 + 1, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Log-File-Rec-Written", COB_SET_FLD (f0, 6, b_104 + 2, &a_15), 0, 0);
  cob_dump_field_ext ( 1, "File-Access", COB_SET_FLD (f0, 2065, b_110, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "We-Error", COB_SET_FLD (f0, 3, b_110, &a_17), 0, 0);
  cob_dump_field_ext ( 3, "Rrn", COB_SET_FLD (f0, 4, b_110 + 3, &a_18), 0, 0);
  cob_dump_field_ext ( 3, "fs-reply", &f_113, 0, 0);
  cob_dump_field_ext ( 3, "s1", COB_SET_FLD (f0, 1, b_110 + 9, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Curs", COB_SET_FLD (f0, 4, b_110 + 10, &a_4), 0, 0);
  cob_dump_field_ext ( 3, "Curs2", COB_SET_FLD (f0, 4, b_110 + 14, &a_4), 0, 0);
  cob_dump_field_ext ( 3, "ACAS-Path", &f_123, 0, 0);
  cob_dump_field_ext ( 3, "Path-Work", COB_SET_FLD (f0, 525, b_110 + 543, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "FS-Action", COB_SET_FLD (f0, 22, b_110 + 1068, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Logging-Data", COB_SET_FLD (f0, 832, b_110 + 1090, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Accept-Reply", COB_SET_FLD (f0, 1, b_110 + 1090, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "File-Key-No", COB_SET_FLD (f0, 1, b_110 + 1091, &a_9), 0, 0);
  cob_dump_field_ext ( 5, "ws-Log-System", &f_129, 0, 0);
  cob_dump_field_ext ( 5, "ws-No-Paragraph", COB_SET_FLD (f0, 3, b_110 + 1093, &a_17), 0, 0);
  cob_dump_field_ext ( 5, "SQL-Err", COB_SET_FLD (f0, 5, b_110 + 1096, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "SQL-Msg", COB_SET_FLD (f0, 512, b_110 + 1101, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "SQL-State", COB_SET_FLD (f0, 5, b_110 + 1613, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-File-Key", COB_SET_FLD (f0, 64, b_110 + 1618, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-Log-Where", COB_SET_FLD (f0, 231, b_110 + 1682, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-Log-File-No", &f_136, 0, 0);
  cob_dump_field_ext ( 5, "WS-Count-Rows", COB_SET_FLD (f0, 7, b_110 + 1915, &a_19), 0, 0);
  cob_dump_field_ext ( 3, "RDB-Data", COB_SET_FLD (f0, 137, b_110 + 1922, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "DB-Schema", COB_SET_FLD (f0, 12, b_110 + 1922, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-UName", COB_SET_FLD (f0, 12, b_110 + 1934, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-UPass", COB_SET_FLD (f0, 12, b_110 + 1946, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Host", COB_SET_FLD (f0, 32, b_110 + 1958, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Socket", COB_SET_FLD (f0, 64, b_110 + 1990, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Port", COB_SET_FLD (f0, 5, b_110 + 2054, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Main-Record-Move-Flag", COB_SET_FLD (f0, 1, b_110 + 2059, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "FA-RDBMS-Flat-Statuses", COB_SET_FLD (f0, 2, b_110 + 2060, &a_5), 0, 0);
  cob_dump_field_ext ( 7, "FA-File-System-Used", COB_SET_FLD (f0, 1, b_110 + 2060, &a_9), 0, 0);
  cob_dump_field_ext ( 7, "FA-File-Duplicates-In-Use", COB_SET_FLD (f0, 1, b_110 + 2061, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "File-Function", COB_SET_FLD (f0, 2, b_110 + 2062, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Access-Type", COB_SET_FLD (f0, 1, b_110 + 2064, &a_9), 0, 0);
  cob_dump_field_ext ( 1, "File-Defs", COB_SET_FLD (f0, 20751, b_181, &a_5), 0, 0);
  cob_dump_field_ext ( 2, "file-defs-a", COB_SET_FLD (f0, 20748, b_181, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "pre-trans-name", COB_SET_FLD (f0, 532, b_181, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "post-trans-name", COB_SET_FLD (f0, 532, b_181 + 532, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-0", COB_SET_FLD (f0, 532, b_181 + 1064, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-2", COB_SET_FLD (f0, 532, b_181 + 1596, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-3", COB_SET_FLD (f0, 532, b_181 + 2128, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-4", COB_SET_FLD (f0, 532, b_181 + 2660, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-5", COB_SET_FLD (f0, 532, b_181 + 3192, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-6", COB_SET_FLD (f0, 532, b_181 + 3724, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-7", &f_191, 0, 0);
  cob_dump_field_ext ( 3, "file-8", COB_SET_FLD (f0, 532, b_181 + 4788, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-9", COB_SET_FLD (f0, 532, b_181 + 5320, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-10", COB_SET_FLD (f0, 532, b_181 + 5852, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-11", COB_SET_FLD (f0, 532, b_181 + 6384, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-12", COB_SET_FLD (f0, 532, b_181 + 6916, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-13", COB_SET_FLD (f0, 532, b_181 + 7448, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-14", COB_SET_FLD (f0, 532, b_181 + 7980, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-15", COB_SET_FLD (f0, 532, b_181 + 8512, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-16", COB_SET_FLD (f0, 532, b_181 + 9044, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-17", COB_SET_FLD (f0, 532, b_181 + 9576, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-18", COB_SET_FLD (f0, 532, b_181 + 10108, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-19", COB_SET_FLD (f0, 532, b_181 + 10640, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-20", COB_SET_FLD (f0, 532, b_181 + 11172, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-21", COB_SET_FLD (f0, 532, b_181 + 11704, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-22", COB_SET_FLD (f0, 532, b_181 + 12236, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-23", COB_SET_FLD (f0, 532, b_181 + 12768, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-24", COB_SET_FLD (f0, 532, b_181 + 13300, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-26", COB_SET_FLD (f0, 532, b_181 + 13832, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-27", COB_SET_FLD (f0, 532, b_181 + 14364, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-28", COB_SET_FLD (f0, 532, b_181 + 14896, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-29", COB_SET_FLD (f0, 532, b_181 + 15428, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-30", COB_SET_FLD (f0, 532, b_181 + 15960, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-31", COB_SET_FLD (f0, 532, b_181 + 16492, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-32", COB_SET_FLD (f0, 532, b_181 + 17024, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-33", COB_SET_FLD (f0, 532, b_181 + 17556, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-34", COB_SET_FLD (f0, 532, b_181 + 18088, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-35", COB_SET_FLD (f0, 532, b_181 + 18620, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-36", COB_SET_FLD (f0, 532, b_181 + 19152, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-37", COB_SET_FLD (f0, 532, b_181 + 19684, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-38", COB_SET_FLD (f0, 532, b_181 + 20216, &a_1), 0, 0);
  cob_dump_field_ext ( 2, "File-Defs-Count", &f_224, 0, 0);
  cob_dump_field_ext ( 2, "File-Defs-os-Delimiter", &f_225, 0, 0);
  cob_dump_field_ext ( 1, "WS-Calling-Data", COB_SET_FLD (f0, 40, b_226, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "WS-Called", COB_SET_FLD (f0, 8, b_226, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Caller", COB_SET_FLD (f0, 8, b_226 + 8, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Del-Link", COB_SET_FLD (f0, 8, b_226 + 16, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Term-Code", COB_SET_FLD (f0, 1, b_226 + 24, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-Process-Func", COB_SET_FLD (f0, 1, b_226 + 25, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-Sub-Function", COB_SET_FLD (f0, 1, b_226 + 26, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-CD-Args", &f_233, 0, 0);
  cob_dump_field_ext ( 1, "Error-Messages", COB_SET_FLD (f0, 184, b_234, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "SY003", &f_235, 0, 0);
  cob_dump_field_ext ( 3, "SY006", &f_236, 0, 0);
  cob_dump_field_ext ( 3, "SY007", &f_237, 0, 0);
  cob_dump_field_ext ( 3, "SY008", &f_238, 0, 0);
  cob_dump_field_ext ( 3, "SY009", &f_239, 0, 0);

  cob_dump_output ("END OF DUMP - glbatchUNL");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'glbatchUNL' */

/* Initialize module structure for glbatchUNL */
static void glbatchUNL_module_init (cob_module *module)
{
  module->module_name = "glbatchUNL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())glbatchUNL;
  module->module_cancel.funcptr = (void *(*)())glbatchUNL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

