/* Generated by           cobc 3.2.0 */
/* Generated from         otm5UNL.cbl */
/* Generated at           Aug 31 2025 13:50:58 */
/* GnuCOBOL build date    Aug 19 2025 17:45:51 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -Wlinkage -lz -I ../copybooks -d -g -ftraceall -fdump=ALL otm5UNL.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"otm5UNL.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Aug 31 2025 13:50:58"
#define  COB_MODULE_DATE		20250831
#define  COB_MODULE_TIME		135058

/* Global variables */
#include "otm5UNL.c.h"

/* Function prototypes */

static int		otm5UNL ();
static int		otm5UNL_ (const int);
static void		otm5UNL_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (otm5UNL ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'otm5UNL' */

/* ENTRY 'otm5UNL' */

static int
otm5UNL ()
{
  return otm5UNL_ (0);
}

static int
otm5UNL_ (const int entry)
{
  /* Program local variables */
  #include "otm5UNL.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "otm5UNL";
  module->frame_ptr->module_stmt = 0x0010009A;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 154       : Entry     otm5UNL                 : otm5UNL.cbl */
  l_2:;
#line 154 "otm5UNL.cbl"
  ENTRY_OTM5UNL:	module->statement = STMT_ENTRY;
#line 109 "otm5UNL.c"
  module->module_stmt = 0x0010009A;
  cob_trace_entry (st_1);
  module->section_name = NULL;
  module->paragraph_name = NULL;
  cob_trace_sect (NULL);

  /* Line: 154       : Paragraph aa000-Main-Start        : otm5UNL.cbl */
#line 154 "otm5UNL.cbl"
  PARAGRAPH_AA000__MAIN__START_l_4:	module->statement = STMT_ENTRY;
#line 119 "otm5UNL.c"
  module->paragraph_name = st_2;
  cob_trace_para (st_2);

  /* Line: 155       : PERFORM            : otm5UNL.cbl */
#line 155 "otm5UNL.cbl"
  module->statement = STMT_PERFORM;
#line 126 "otm5UNL.c"
  module->module_stmt = 0x0010009B;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM zz020-Get-Program-Args */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_11;
  l_17:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 156       : MOVE               : otm5UNL.cbl */
#line 156 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 150 "otm5UNL.c"
  module->module_stmt = 0x0010009C;
  cob_trace_statement (STMT_MOVE);
  *(b_84 + 1092) = 52;

  /* Line: 157       : MOVE               : otm5UNL.cbl */
#line 157 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 158 "otm5UNL.c"
  module->module_stmt = 0x0010009D;
  cob_trace_statement (STMT_MOVE);
  memcpy (b_84 + 1913, "15", 2);

  /* Line: 159       : MOVE               : otm5UNL.cbl */
#line 159 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 166 "otm5UNL.c"
  module->module_stmt = 0x0010009F;
  cob_trace_statement (STMT_MOVE);
  memset (b_77, 32, 160);

  /* Line: 160       : STRING             : otm5UNL.cbl */
#line 160 "otm5UNL.cbl"
  module->statement = STMT_STRING;
#line 174 "otm5UNL.c"
  module->module_stmt = 0x001000A0;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_77, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_64);
  cob_string_append ((cob_field *)&c_1);
  cob_string_append ((cob_field *)&c_2);
  cob_string_finish ();

  /* Line: 162       : PERFORM            : otm5UNL.cbl */
#line 162 "otm5UNL.cbl"
  module->statement = STMT_PERFORM;
#line 187 "otm5UNL.c"
  module->module_stmt = 0x001000A2;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_16;
  l_18:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 166       : OPEN               : otm5UNL.cbl */
#line 166 "otm5UNL.cbl"
  module->statement = STMT_OPEN;
#line 211 "otm5UNL.c"
  module->module_stmt = 0x001000A6;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_OPEN_ITEM_FILE_5, COB_OPEN_INPUT, 0, &f_87);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 167       : IF                 : otm5UNL.cbl */
#line 167 "otm5UNL.cbl"
  module->statement = STMT_IF;
#line 239 "otm5UNL.c"
  module->module_stmt = 0x001000A7;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp_numdisp (b_84 + 7, 2, 0LL, 0) != 0))
  {

    /* Line: 168       : MOVE               : otm5UNL.cbl */
#line 168 "otm5UNL.cbl"
    module->statement = STMT_MOVE;
#line 248 "otm5UNL.c"
    module->module_stmt = 0x001000A8;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_3, &f_77);

    /* Line: 169       : PERFORM            : otm5UNL.cbl */
#line 169 "otm5UNL.cbl"
    module->statement = STMT_PERFORM;
#line 256 "otm5UNL.c"
    module->module_stmt = 0x001000A9;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM Call-Sysout */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_16;
    l_20:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;

    /* Line: 170       : CLOSE              : otm5UNL.cbl */
#line 170 "otm5UNL.cbl"
    module->statement = STMT_CLOSE;
#line 280 "otm5UNL.c"
    module->module_stmt = 0x001000AA;
    cob_trace_statement (STMT_CLOSE);
    cob_close (h_OPEN_ITEM_FILE_5, &f_87, 0, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_21;
      goto l_1;
      l_21:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 171       : MOVE               : otm5UNL.cbl */
#line 171 "otm5UNL.cbl"
    module->statement = STMT_MOVE;
#line 308 "otm5UNL.c"
    module->module_stmt = 0x001000AB;
    cob_trace_statement (STMT_MOVE);
    cob_move ((cob_field *)&c_4, &f_77);

    /* Line: 172       : PERFORM            : otm5UNL.cbl */
#line 172 "otm5UNL.cbl"
    module->statement = STMT_PERFORM;
#line 316 "otm5UNL.c"
    module->module_stmt = 0x001000AC;
    cob_trace_statement (STMT_PERFORM);
    /* PERFORM Call-Sysout */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_16;
    l_22:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;

    /* Line: 173       : GOBACK             : otm5UNL.cbl */
#line 173 "otm5UNL.cbl"
    module->statement = STMT_GOBACK;
#line 340 "otm5UNL.c"
    module->module_stmt = 0x001000AD;
    cob_trace_statement (STMT_GOBACK);
    goto exit_program;
  }

  /* Line: 175       : OPEN               : otm5UNL.cbl */
#line 175 "otm5UNL.cbl"
  module->statement = STMT_OPEN;
#line 349 "otm5UNL.c"
  module->module_stmt = 0x001000AF;
  cob_trace_statement (STMT_OPEN);
  cob_open (h_OTM5_FILE_SEQ, COB_OPEN_OUTPUT, 0, &f_87);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_23;
    goto l_1;
    l_23:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 176       : MOVE               : otm5UNL.cbl */
#line 176 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 377 "otm5UNL.c"
  module->module_stmt = 0x001000B0;
  cob_trace_statement (STMT_MOVE);
  memset (b_73 + 4, 48, 4);
  memset (b_73, 48, 4);

  /* Line: 178       : Paragraph aa010-Read-Recs         : otm5UNL.cbl */
#line 178 "otm5UNL.cbl"
  PARAGRAPH_AA010__READ__RECS_l_5:	module->statement = STMT_ENTRY;
#line 386 "otm5UNL.c"
  module->module_stmt = 0x001000B2;
  module->paragraph_name = st_3;
  cob_trace_para (st_3);

  /* Line: 179       : PERFORM            : otm5UNL.cbl */
#line 179 "otm5UNL.cbl"
  module->statement = STMT_PERFORM;
#line 394 "otm5UNL.c"
  module->module_stmt = 0x001000B3;
  cob_trace_statement (STMT_PERFORM);
  for (;;)
  {

    /* Line: 180       : READ               : otm5UNL.cbl */
#line 180 "otm5UNL.cbl"
    module->statement = STMT_READ;
#line 403 "otm5UNL.c"
    module->module_stmt = 0x001000B4;
    cob_trace_statement (STMT_READ);
    cob_read_next (h_OPEN_ITEM_FILE_5, &f_87, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 181       : GO TO              : otm5UNL.cbl */
#line 181 "otm5UNL.cbl"
        module->statement = STMT_GO_TO;
#line 415 "otm5UNL.c"
        module->module_stmt = 0x001000B5;
        cob_trace_statement (STMT_GO_TO);
        goto l_6;
      }
      else
      {
        /* USE PROCEDURE Default Error Handler */
        frame_ptr++;
        frame_ptr->module_stmt = module->module_stmt;
        frame_ptr->section_name = module->section_name;
        frame_ptr->paragraph_name = module->paragraph_name;
        module->frame_ptr = frame_ptr;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_24;
        goto l_1;
        l_24:
        frame_ptr--;
        module->module_stmt = module->frame_ptr->module_stmt;
        module->section_name = module->frame_ptr->section_name;
        module->paragraph_name = module->frame_ptr->paragraph_name;
        module->frame_ptr = frame_ptr;
      }
    }

    /* Line: 183       : IF                 : otm5UNL.cbl */
#line 183 "otm5UNL.cbl"
    module->statement = STMT_IF;
#line 445 "otm5UNL.c"
    module->module_stmt = 0x001000B7;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_84 + 7, 2, 0LL, 0) != 0))
    {

      /* Line: 184       : STRING             : otm5UNL.cbl */
#line 184 "otm5UNL.cbl"
      module->statement = STMT_STRING;
#line 454 "otm5UNL.c"
      module->module_stmt = 0x001000B8;
      cob_trace_statement (STMT_STRING);
      cob_string_init (&f_77, NULL);
      cob_string_delimited (NULL);
      cob_string_append (&f_209);
      cob_string_append (&f_87);
      cob_string_finish ();

      /* Line: 188       : PERFORM            : otm5UNL.cbl */
#line 188 "otm5UNL.cbl"
      module->statement = STMT_PERFORM;
#line 466 "otm5UNL.c"
      module->module_stmt = 0x001000BC;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM Call-Sysout */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 16;
      frame_ptr->return_address_ptr = &&l_25;
      goto l_16;
      l_25:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;

      /* Line: 189       : GO TO              : otm5UNL.cbl */
#line 189 "otm5UNL.cbl"
      module->statement = STMT_GO_TO;
#line 490 "otm5UNL.c"
      module->module_stmt = 0x001000BD;
      cob_trace_statement (STMT_GO_TO);
      goto l_6;
    }

    /* Line: 191       : ADD                : otm5UNL.cbl */
#line 191 "otm5UNL.cbl"
    module->statement = STMT_ADD;
#line 499 "otm5UNL.c"
    module->module_stmt = 0x001000BF;
    cob_trace_statement (STMT_ADD);
    cob_check_numeric (&f_74, "ws-Rec-Cnt-In");
    cob_add_int (&f_74, 1, 0);

    /* Line: 192       : WRITE              : otm5UNL.cbl */
#line 192 "otm5UNL.cbl"
    module->statement = STMT_WRITE;
#line 508 "otm5UNL.c"
    module->module_stmt = 0x001000C0;
    cob_trace_statement (STMT_WRITE);
    cob_move (&f_17, &f_62);
    cob_write (h_OTM5_FILE_SEQ, &f_62, 0, &f_87, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* USE PROCEDURE Default Error Handler */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_26;
      goto l_1;
      l_26:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;
    }

    /* Line: 193       : IF                 : otm5UNL.cbl */
#line 193 "otm5UNL.cbl"
    module->statement = STMT_IF;
#line 537 "otm5UNL.c"
    module->module_stmt = 0x001000C1;
    cob_trace_statement (STMT_IF);
    if (((int)cob_cmp_numdisp (b_84 + 7, 2, 0LL, 0) != 0))
    {

      /* Line: 194       : MOVE               : otm5UNL.cbl */
#line 194 "otm5UNL.cbl"
      module->statement = STMT_MOVE;
#line 546 "otm5UNL.c"
      module->module_stmt = 0x001000C2;
      cob_trace_statement (STMT_MOVE);
      cob_move (&f_210, &f_77);

      /* Line: 195       : PERFORM            : otm5UNL.cbl */
#line 195 "otm5UNL.cbl"
      module->statement = STMT_PERFORM;
#line 554 "otm5UNL.c"
      module->module_stmt = 0x001000C3;
      cob_trace_statement (STMT_PERFORM);
      /* PERFORM Call-Sysout */
      frame_ptr++;
      frame_ptr->module_stmt = module->module_stmt;
      frame_ptr->section_name = module->section_name;
      frame_ptr->paragraph_name = module->paragraph_name;
      module->frame_ptr = frame_ptr;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 16;
      frame_ptr->return_address_ptr = &&l_27;
      goto l_16;
      l_27:
      frame_ptr--;
      module->module_stmt = module->frame_ptr->module_stmt;
      module->section_name = module->frame_ptr->section_name;
      module->paragraph_name = module->frame_ptr->paragraph_name;
      module->frame_ptr = frame_ptr;

      /* Line: 196       : GO TO              : otm5UNL.cbl */
#line 196 "otm5UNL.cbl"
      module->statement = STMT_GO_TO;
#line 578 "otm5UNL.c"
      module->module_stmt = 0x001000C4;
      cob_trace_statement (STMT_GO_TO);
      goto l_6;
    }

    /* Line: 198       : ADD                : otm5UNL.cbl */
#line 198 "otm5UNL.cbl"
    module->statement = STMT_ADD;
#line 587 "otm5UNL.c"
    module->module_stmt = 0x001000C6;
    cob_trace_statement (STMT_ADD);
    cob_check_numeric (&f_75, "ws-Rec-Cnt-Out");
    cob_add_int (&f_75, 1, 0);
  }

  /* Line: 201       : Paragraph aa020-Finish-Off        : otm5UNL.cbl */
  l_6:;
#line 201 "otm5UNL.cbl"
  PARAGRAPH_AA020__FINISH__OFF_l_6:	module->statement = STMT_ENTRY;
#line 598 "otm5UNL.c"
  module->module_stmt = 0x001000C9;
  module->paragraph_name = st_4;
  cob_trace_para (st_4);

  /* Line: 202       : CLOSE              : otm5UNL.cbl */
#line 202 "otm5UNL.cbl"
  module->statement = STMT_CLOSE;
#line 606 "otm5UNL.c"
  module->module_stmt = 0x001000CA;
  cob_trace_statement (STMT_CLOSE);
  cob_close (h_OTM5_FILE_SEQ, &f_87, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }
  cob_close (h_OPEN_ITEM_FILE_5, &f_87, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* USE PROCEDURE Default Error Handler */
    frame_ptr++;
    frame_ptr->module_stmt = module->module_stmt;
    frame_ptr->section_name = module->section_name;
    frame_ptr->paragraph_name = module->paragraph_name;
    module->frame_ptr = frame_ptr;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_1;
    l_29:
    frame_ptr--;
    module->module_stmt = module->frame_ptr->module_stmt;
    module->section_name = module->frame_ptr->section_name;
    module->paragraph_name = module->frame_ptr->paragraph_name;
    module->frame_ptr = frame_ptr;
  }

  /* Line: 204       : MOVE               : otm5UNL.cbl */
#line 204 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 655 "otm5UNL.c"
  module->module_stmt = 0x001000CC;
  cob_trace_statement (STMT_MOVE);
  memset (b_77, 32, 160);

  /* Line: 205       : STRING             : otm5UNL.cbl */
#line 205 "otm5UNL.cbl"
  module->statement = STMT_STRING;
#line 663 "otm5UNL.c"
  module->module_stmt = 0x001000CD;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_77, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_5);
  cob_string_append (&f_74);
  cob_string_append ((cob_field *)&c_6);
  cob_string_append (&f_75);
  cob_string_finish ();

  /* Line: 211       : PERFORM            : otm5UNL.cbl */
#line 211 "otm5UNL.cbl"
  module->statement = STMT_PERFORM;
#line 677 "otm5UNL.c"
  module->module_stmt = 0x001000D3;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_30;
  goto l_16;
  l_30:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 212       : MOVE               : otm5UNL.cbl */
#line 212 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 701 "otm5UNL.c"
  module->module_stmt = 0x001000D4;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_4, &f_77);

  /* Line: 213       : PERFORM            : otm5UNL.cbl */
#line 213 "otm5UNL.cbl"
  module->statement = STMT_PERFORM;
#line 709 "otm5UNL.c"
  module->module_stmt = 0x001000D5;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM Call-Sysout */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_31;
  goto l_16;
  l_31:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 214       : MOVE               : otm5UNL.cbl */
#line 214 "otm5UNL.cbl"
  module->statement = STMT_MOVE;
#line 733 "otm5UNL.c"
  module->module_stmt = 0x001000D6;
  cob_trace_statement (STMT_MOVE);
  b_2 = 0;

  /* Line: 215       : GOBACK             : otm5UNL.cbl */
#line 215 "otm5UNL.cbl"
  module->statement = STMT_GOBACK;
#line 741 "otm5UNL.c"
  module->module_stmt = 0x001000D7;
  cob_trace_statement (STMT_GOBACK);
  goto exit_program;

  /* Line: 17        : Section   zz010-Get-Env-Set-Files : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_7:;
#line 17 "../copybooks/Proc-Get-Env-Set-Files.cob"
  SECTION_ZZ010__GET__ENV__SET__FILES:	cob_nop ();
#line 750 "otm5UNL.c"
  module->module_stmt = 0x00200011;
  module->section_name = st_5;
  module->paragraph_name = NULL;
  cob_trace_sect (st_5);
  cob_trace_para (NULL);

  /* Line: 20        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 20 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 760 "otm5UNL.c"
  module->module_stmt = 0x00200014;
  cob_trace_statement (STMT_ACCEPT);
  cob_get_environment ((cob_field *)&c_7, &f_68);

  /* Line: 21        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 21 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 768 "otm5UNL.c"
  module->module_stmt = 0x00200015;
  cob_trace_statement (STMT_ACCEPT);
  cob_get_environment ((cob_field *)&c_8, &f_67);

  /* Line: 23        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 23 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 776 "otm5UNL.c"
  module->module_stmt = 0x00200017;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_68 + 0LL) - ' ') == 0) || 
      ((int)(int)(*(b_67 + 0LL) - ' ') == 0)))
  {

    /* Line: 25        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 25 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 786 "otm5UNL.c"
    module->module_stmt = 0x00200019;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_213, 5120, "p", (cob_field *)&c_9);

    /* Line: 26        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 26 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 794 "otm5UNL.c"
    module->module_stmt = 0x0020001A;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_212, 4096, "pf", (cob_field *)&c_10, (cob_field *)&c_11);

    /* Line: 27        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 27 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ACCEPT;
#line 802 "otm5UNL.c"
    module->module_stmt = 0x0020001B;
    cob_trace_statement (STMT_ACCEPT);
    cob_accept_field (&f_76, 0, "p", (cob_field *)&c_12);

    /* Line: 28        : STOP RUN           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 28 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STOP_RUN;
#line 810 "otm5UNL.c"
    module->module_stmt = 0x0020001C;
    cob_trace_statement (STMT_STOP_RUN);
    cob_stop_run (b_2);
  }

  /* Line: 30        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 30 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 819 "otm5UNL.c"
  module->module_stmt = 0x0020001E;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_68 + 0LL) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_68 + 0LL) - (unsigned char)'/') == 0)))
  {

    /* Line: 31        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 31 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 829 "otm5UNL.c"
    module->module_stmt = 0x0020001F;
    cob_trace_statement (STMT_MOVE);
    *(b_66) = *(b_68 + 0LL);
  }

  /* Line: 34        : Paragraph zz010-GESF-Exit         : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 34 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ010__GESF__EXIT_l_9:	module->statement = STMT_ENTRY;
#line 838 "otm5UNL.c"
  module->module_stmt = 0x00200022;
  module->paragraph_name = st_6;
  cob_trace_para (st_6);

  /* Line: 35        : EXIT SECTION       : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 35 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_EXIT_SECTION;
#line 846 "otm5UNL.c"
  module->module_stmt = 0x00200023;
  cob_trace_statement (STMT_EXIT_SECTION);
  goto l_10;

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 37        : Section   zz020-Get-Program-Args  : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_11:;
#line 37 "../copybooks/Proc-Get-Env-Set-Files.cob"
  SECTION_ZZ020__GET__PROGRAM__ARGS:	cob_nop ();
#line 862 "otm5UNL.c"
  module->module_stmt = 0x00200025;
  module->section_name = st_7;
  module->paragraph_name = NULL;
  cob_trace_sect (st_7);
  cob_trace_para (NULL);

  /* Line: 40        : PERFORM            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 40 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_PERFORM;
#line 872 "otm5UNL.c"
  module->module_stmt = 0x00200028;
  cob_trace_statement (STMT_PERFORM);
  /* PERFORM zz010-Get-Env-Set-Files */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_32;
  goto l_7;
  l_32:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 47        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 47 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 896 "otm5UNL.c"
  module->module_stmt = 0x0020002F;
  cob_trace_statement (STMT_MOVE);
  memset (b_72, 32, 525);
  memset (b_200 + 27, 32, 13);

  /* Line: 49        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 49 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 905 "otm5UNL.c"
  module->module_stmt = 0x00200031;
  cob_trace_statement (STMT_MOVE);
  cob_move ((cob_field *)&c_13, &f_65);

  /* Line: 50        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 50 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_ACCEPT;
#line 913 "otm5UNL.c"
  module->module_stmt = 0x00200032;
  cob_trace_statement (STMT_ACCEPT);
  cob_accept_command_line (&f_70);

  /* Line: 51        : UNSTRING           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 51 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_UNSTRING;
#line 921 "otm5UNL.c"
  module->module_stmt = 0x00200033;
  cob_trace_statement (STMT_UNSTRING);
  cob_unstring_init (&f_70, &f_65, 1);
  cob_unstring_delimited (&cob_all_space, 0);
  cob_unstring_into (&f_72, 0, 0);
  cob_unstring_finish ();

  /* Line: 60        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 60 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 932 "otm5UNL.c"
  module->module_stmt = 0x0020003C;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_72 + 0LL, COB_SPACES_ALPHABETIC, 5) == 0))
  {

    /* Line: 61        : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 61 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 941 "otm5UNL.c"
    module->module_stmt = 0x0020003D;
    cob_trace_statement (STMT_GO_TO);
    goto l_13;
  }

  /* Line: 73        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 73 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 950 "otm5UNL.c"
  module->module_stmt = 0x00200049;
  cob_trace_statement (STMT_IF);
  if (((((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"ACAS_LEDGERS", 12) != 0) && 
      ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"NULL", 4) != 0)) && 
      ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"NONE", 4) != 0)))
  {

    /* Line: 75        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 75 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 961 "otm5UNL.c"
    module->module_stmt = 0x0020004B;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_211, 1024, "pf", (cob_field *)&c_14, (cob_field *)&c_11);

    /* Line: 76        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 76 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 969 "otm5UNL.c"
    module->module_stmt = 0x0020004C;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_15, 0, "pf", (cob_field *)&c_16, (cob_field *)&c_17);

    /* Line: 77        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 77 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 977 "otm5UNL.c"
    module->module_stmt = 0x0020004D;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_69, 0, "pf", (cob_field *)&c_18, (cob_field *)&c_17);

    /* Line: 78        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 78 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 985 "otm5UNL.c"
    module->module_stmt = 0x0020004E;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field ((cob_field *)&c_19, 0, "pf", (cob_field *)&c_20, (cob_field *)&c_17);

    /* Line: 79        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 79 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 993 "otm5UNL.c"
    module->module_stmt = 0x0020004F;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (COB_SET_FLD (f0, 40, b_72 + 0LL, &a_1), 0, "pf", (cob_field *)&c_21, (cob_field *)&c_17);

    /* Line: 80        : DISPLAY            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 80 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_DISPLAY;
#line 1001 "otm5UNL.c"
    module->module_stmt = 0x00200050;
    cob_trace_statement (STMT_DISPLAY);
    cob_display_field (&f_212, 4096, "pf", (cob_field *)&c_10, (cob_field *)&c_11);

    /* Line: 81        : ACCEPT             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 81 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ACCEPT;
#line 1009 "otm5UNL.c"
    module->module_stmt = 0x00200051;
    cob_trace_statement (STMT_ACCEPT);
    cob_accept_field (&f_76, 0, "p", (cob_field *)&c_12);

    /* Line: 82        : STOP RUN           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 82 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STOP_RUN;
#line 1017 "otm5UNL.c"
    module->module_stmt = 0x00200052;
    cob_trace_statement (STMT_STOP_RUN);
    cob_stop_run (b_2);
  }

  /* Line: 84        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 84 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1026 "otm5UNL.c"
  module->module_stmt = 0x00200054;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"ACAS_LEDGERS=", 13) == 0))
  {

    /* Line: 85        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 85 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1035 "otm5UNL.c"
    module->module_stmt = 0x00200055;
    cob_trace_statement (STMT_MOVE);
    cob_move (cob_intr_trim (0, 0, COB_SET_FLD (f0, 487, b_72 + 13LL, &a_1), 2), &f_68);
  }

  /* Line: 93        : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 93 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1044 "otm5UNL.c"
  module->module_stmt = 0x0020005D;
  cob_trace_statement (STMT_MOVE);
  memset (b_72, 32, 525);

  /* Line: 94        : UNSTRING           : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 94 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_UNSTRING;
#line 1052 "otm5UNL.c"
  module->module_stmt = 0x0020005E;
  cob_trace_statement (STMT_UNSTRING);
  cob_unstring_init (&f_70, &f_65, 1);
  cob_unstring_delimited (&cob_all_space, 0);
  cob_unstring_into (&f_72, 0, 0);
  cob_unstring_finish ();

  /* Line: 98        : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 98 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1063 "otm5UNL.c"
  module->module_stmt = 0x00200062;
  cob_trace_statement (STMT_IF);
  if (((int)memcmp (b_72 + 0LL, COB_SPACES_ALPHABETIC, 4) != 0))
  {

    /* Line: 103       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 103 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_IF;
#line 1072 "otm5UNL.c"
    module->module_stmt = 0x00200067;
    cob_trace_statement (STMT_IF);
    if ((((((((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"st020", 5) == 0) || 
        ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"ST020", 5) == 0)) || 
        ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"st040", 5) == 0)) || 
        ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"ST040", 5) == 0)) || 
        ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"xl150", 5) == 0)) || 
        ((int)memcmp (b_72 + 0LL, (cob_u8_ptr)"XL150", 5) == 0)))
    {

      /* Line: 106       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 106 "../copybooks/Proc-Get-Env-Set-Files.cob"
      module->statement = STMT_MOVE;
#line 1086 "otm5UNL.c"
      module->module_stmt = 0x0020006A;
      cob_trace_statement (STMT_MOVE);
      cob_move (cob_intr_lower_case (0, 0, COB_SET_FLD (f0, 13, b_72 + 0LL, &a_1)), &f_207);
    }
  }

  /* Line: 110       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 110 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1096 "otm5UNL.c"
  module->module_stmt = 0x0020006E;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_68 + 0LL) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_68 + 0LL) - (unsigned char)'/') == 0)))
  {

    /* Line: 111       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 111 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1106 "otm5UNL.c"
    module->module_stmt = 0x0020006F;
    cob_trace_statement (STMT_MOVE);
    *(b_66) = *(b_68 + 0LL);
  }

  /* Line: 118       : Paragraph zz020-Set-the-Paths     : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_13:;
#line 118 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ020__SET__THE__PATHS_l_13:	module->statement = STMT_ENTRY;
#line 1116 "otm5UNL.c"
  module->module_stmt = 0x00200076;
  module->paragraph_name = st_8;
  cob_trace_para (st_8);

  /* Line: 119       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 119 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1124 "otm5UNL.c"
  module->module_stmt = 0x00200077;
  cob_trace_statement (STMT_IF);
  if (((int)cob_cmp (cob_intr_module_caller_id (), (cob_field *)&c_22) == 0))
  {

    /* Line: 120       : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 120 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 1133 "otm5UNL.c"
    module->module_stmt = 0x00200078;
    cob_trace_statement (STMT_GO_TO);
    goto l_14;
  }

  /* Line: 122       : IF                 : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 122 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_IF;
#line 1142 "otm5UNL.c"
  module->module_stmt = 0x0020007A;
  cob_trace_statement (STMT_IF);
  if ((((int)(int)(*(b_155 + 20750) - (unsigned char)'\\') == 0) || 
      ((int)(int)(*(b_155 + 20750) - (unsigned char)'/') == 0)))
  {

    /* Line: 123       : GO TO              : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 123 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_GO_TO;
#line 1152 "otm5UNL.c"
    module->module_stmt = 0x0020007B;
    cob_trace_statement (STMT_GO_TO);
    goto l_14;
  }

  /* Line: 127       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 127 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1161 "otm5UNL.c"
  module->module_stmt = 0x0020007F;
  cob_trace_statement (STMT_MOVE);
  (*(cob_s8_ptr) (b_65)) = 0;

  /* Line: 128       : PERFORM            : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 128 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_PERFORM;
#line 1169 "otm5UNL.c"
  module->module_stmt = 0x00200080;
  cob_trace_statement (STMT_PERFORM);
  for (n0 = (*(short *)(b_155 + 20748)); n0 > 0; n0--)
  {

    /* Line: 129       : ADD                : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 129 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_ADD;
#line 1178 "otm5UNL.c"
    module->module_stmt = 0x00200081;
    cob_trace_statement (STMT_ADD);
    cob_add_s8 (b_65, 1);

    /* Line: 130       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 130 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1186 "otm5UNL.c"
    module->module_stmt = 0x00200082;
    cob_trace_statement (STMT_MOVE);
    memset (b_72, 32, 525);

    /* Line: 131       : STRING             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 131 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_STRING;
#line 1194 "otm5UNL.c"
    module->module_stmt = 0x00200083;
    cob_trace_statement (STMT_STRING);
    cob_string_init (&f_72, NULL);
    cob_string_delimited (&cob_all_space);
    cob_string_append (&f_68);
    cob_string_delimited (NULL);
    cob_string_append (&f_66);
    cob_string_delimited (&cob_all_space);
    cob_string_append (
    (cob_check_subscript ((*(cob_s8_ptr) (b_65)), 39, "System-File-Names", 0),
    COB_SET_FLD (f0, 532, b_155 + 532LL * ((cob_s64_t)((*(cob_s8_ptr) (b_65))) - 1), &a_1) ));
    cob_string_finish ();

    /* Line: 136       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 136 "../copybooks/Proc-Get-Env-Set-Files.cob"
    module->statement = STMT_MOVE;
#line 1211 "otm5UNL.c"
    module->module_stmt = 0x00200088;
    cob_trace_statement (STMT_MOVE);
    cob_check_subscript ((*(cob_s8_ptr) (b_65)), 39, "System-File-Names", 0);
    cob_move (&f_72, COB_SET_FLD (f0, 532, b_155 + 532LL * ((cob_s64_t)((*(cob_s8_ptr) (b_65))) - 1), &a_1));
  }

  /* Line: 138       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 138 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1221 "otm5UNL.c"
  module->module_stmt = 0x0020008A;
  cob_trace_statement (STMT_MOVE);
  (*(cob_s8_ptr) (b_65)) = 0;

  /* Line: 139       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 139 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1229 "otm5UNL.c"
  module->module_stmt = 0x0020008B;
  cob_trace_statement (STMT_MOVE);
  *(b_155 + 20750) = *(b_66);

  /* Line: 141       : MOVE               : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 141 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_MOVE;
#line 1237 "otm5UNL.c"
  module->module_stmt = 0x0020008D;
  cob_trace_statement (STMT_MOVE);
  memset (b_84 + 18, 32, 525);

  /* Line: 142       : STRING             : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 142 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_STRING;
#line 1245 "otm5UNL.c"
  module->module_stmt = 0x0020008E;
  cob_trace_statement (STMT_STRING);
  cob_string_init (&f_97, NULL);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_68);
  cob_string_delimited (NULL);
  cob_string_append (&f_66);
  cob_string_finish ();

  /* Line: 146       : Paragraph zz020-Exit              : ../copybooks/Proc-Get-Env-Set-Files.cob */
  l_14:;
#line 146 "../copybooks/Proc-Get-Env-Set-Files.cob"
  PARAGRAPH_ZZ020__EXIT_l_14:	module->statement = STMT_ENTRY;
#line 1259 "otm5UNL.c"
  module->module_stmt = 0x00200092;
  module->paragraph_name = st_9;
  cob_trace_para (st_9);

  /* Line: 147       : EXIT SECTION       : ../copybooks/Proc-Get-Env-Set-Files.cob */
#line 147 "../copybooks/Proc-Get-Env-Set-Files.cob"
  module->statement = STMT_EXIT_SECTION;
#line 1267 "otm5UNL.c"
  module->module_stmt = 0x00200093;
  cob_trace_statement (STMT_EXIT_SECTION);
  goto l_15;

  /* Line: 219       : Paragraph Call-Sysout             : otm5UNL.cbl */
  l_16:;
#line 219 "otm5UNL.cbl"
  PARAGRAPH_CALL__SYSOUT_l_16:	module->statement = STMT_ENTRY;
#line 1276 "otm5UNL.c"
  module->module_stmt = 0x001000DB;
  module->paragraph_name = st_10;
  cob_trace_para (st_10);

  /* Line: 220       : CALL               : otm5UNL.cbl */
#line 220 "otm5UNL.cbl"
  module->statement = STMT_CALL;
#line 1284 "otm5UNL.c"
  module->module_stmt = 0x001000DC;
  cob_trace_statement (STMT_CALL);
  cob_procedure_params[0] = &f_77;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
  if (memcmp (b_77_fence_pre, "\x00\x00\x00\x00\x00\x00\x00", 8) == 0) {
    memcpy (b_77_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
    memcpy (b_77_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);
  } else {
    cob_check_fence (b_77_fence_pre, b_77_fence_post, STMT_BEFORE_CALL, "SO-Print");
  }
    if (unlikely(call_ACAS__Sysout.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_ACAS__Sysout.funcvoid = cob_resolve_cobol ("ACAS-Sysout", 0, 1);
  }
  b_2 = ((int (*)(void *))call_ACAS__Sysout.funcint) (b_77);
  cob_check_fence (b_77_fence_pre, b_77_fence_post, STMT_CALL, "SO-Print");
  cob_check_fence (call_fence_pre, call_fence_post, STMT_CALL, NULL);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Implicit EXIT label */
  l_15:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 222       : last source line                  :otm5UNL.cbl */
#line 222 "otm5UNL.cbl"
  module->module_stmt = 0x001000DE;
#line 1319 "otm5UNL.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : otm5UNL.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  otm5UNL_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = &f_214;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize call-pointer memory fence */
  memcpy (call_fence_pre, "\xFF\xFE\xFD\xFC\xFB\xFA\xFF", 8);
  memcpy (call_fence_post, "\xFA\xFB\xFC\xFD\xFE\xFF\xFA", 8);

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field prog-name */
#line 119 "otm5UNL.cbl"
  cob_nop ();
#line 1395 "otm5UNL.c"
  memcpy (b_64, "otm5UNL (3.02.00)     ", 22);

  /* initialize field z */
#line 120 "otm5UNL.cbl"
  cob_nop ();
#line 1401 "otm5UNL.c"
  (*(cob_s8_ptr) (b_65)) = 0;

  /* initialize field OS-Delimiter */
#line 121 "otm5UNL.cbl"
  cob_nop ();
#line 1407 "otm5UNL.c"
  *(cob_u8_ptr)(b_66) = (unsigned char)'/';

  /* initialize field ACAS_BIN */
#line 122 "otm5UNL.cbl"
  cob_nop ();
#line 1413 "otm5UNL.c"
  memset (b_67, 32, 512);

  /* initialize field ACAS_LEDGERS */
#line 123 "otm5UNL.cbl"
  cob_nop ();
#line 1419 "otm5UNL.c"
  memset (b_68, 32, 500);

  /* initialize field Arg-Number */
#line 124 "otm5UNL.cbl"
  cob_nop ();
#line 1425 "otm5UNL.c"
  *(cob_u8_ptr)(b_69) = 48;

  /* initialize field Arg-Vals */
#line 127 "otm5UNL.cbl"
  cob_nop ();
#line 1431 "otm5UNL.c"
  memset (b_70, 32, 1050);

  /* initialize field Arg-Test */
#line 129 "otm5UNL.cbl"
  cob_nop ();
#line 1437 "otm5UNL.c"
  memset (b_72, 32, 525);

  /* initialize field ws-Rec-Cnt-In */
#line 132 "otm5UNL.cbl"
  cob_nop ();
#line 1443 "otm5UNL.c"
  memset (b_73, 48, 4);
  /* initialize field ws-Rec-Cnt-Out */
#line 133 "otm5UNL.cbl"
  cob_nop ();
#line 1448 "otm5UNL.c"
  memset (b_73 + 4, 48, 4);
  /* initialize field ws-reply */
#line 134 "otm5UNL.cbl"
  cob_nop ();
#line 1453 "otm5UNL.c"
  *(cob_u8_ptr)(b_73 + 8) = (unsigned char)' ';

  /* initialize field SO-Print */
#line 136 "otm5UNL.cbl"
  cob_nop ();
#line 1459 "otm5UNL.c"
  memset (b_77, 32, 160);

  /* initialize field SW-Testing */
#line 10 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1465 "otm5UNL.c"
  *(b_78) = 49;
  /* initialize field SW-Testing-2 */
#line 15 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1470 "otm5UNL.c"
  *(cob_u8_ptr)(b_78 + 1) = 48;
  /* initialize field Log-File-Rec-Written */
#line 18 "../copybooks/Test-Data-Flags.cob"
  cob_nop ();
#line 1475 "otm5UNL.c"
  memset (b_78 + 2, 48, 6);

  /* initialize field We-Error */
#line 23 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1481 "otm5UNL.c"
  memset (b_84, (unsigned char)'0', 3);
  /* initialize field Rrn */
#line 24 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1486 "otm5UNL.c"
  memset (b_84 + 3, 0x0, 4);
  /* initialize field fs-reply */
#line 25 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1491 "otm5UNL.c"
  memset (b_84 + 7, (unsigned char)'0', 2);
  /* initialize field s1 */
#line 26 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1496 "otm5UNL.c"
  *(cob_u8_ptr)(b_84 + 9) = (unsigned char)' ';
  /* initialize field Curs */
#line 27 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1501 "otm5UNL.c"
  memset (b_84 + 10, (unsigned char)'0', 8);
  /* initialize field ACAS-Path */
#line 38 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1506 "otm5UNL.c"
  memset (b_84 + 18, 32, 525);
  /* initialize field Path-Work */
#line 39 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1511 "otm5UNL.c"
  memset (b_84 + 543, 32, 525);
  /* initialize field FS-Action */
#line 41 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1516 "otm5UNL.c"
  memset (b_84 + 1068, 32, 22);
  /* initialize field Accept-Reply */
#line 45 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1521 "otm5UNL.c"
  *(cob_u8_ptr)(b_84 + 1090) = 32;
  /* initialize field File-Key-No */
#line 46 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1526 "otm5UNL.c"
  *(cob_u8_ptr)(b_84 + 1091) = (unsigned char)'0';
  /* initialize field ws-Log-System */
#line 47 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1531 "otm5UNL.c"
  *(cob_u8_ptr)(b_84 + 1092) = 48;
  /* initialize field ws-No-Paragraph */
#line 48 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1536 "otm5UNL.c"
  memset (b_84 + 1093, (unsigned char)'0', 3);
  /* initialize field SQL-Err */
#line 49 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1541 "otm5UNL.c"
  memset (b_84 + 1096, (unsigned char)' ', 5);
  /* initialize field SQL-Msg */
#line 50 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1546 "otm5UNL.c"
  memset (b_84 + 1101, 32, 512);
  /* initialize field SQL-State */
#line 51 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1551 "otm5UNL.c"
  memset (b_84 + 1613, (unsigned char)' ', 5);
  /* initialize field WS-File-Key */
#line 52 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1556 "otm5UNL.c"
  memset (b_84 + 1618, 32, 64);
  /* initialize field WS-Log-Where */
#line 53 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1561 "otm5UNL.c"
  memset (b_84 + 1682, 32, 231);
  /* initialize field WS-Log-File-No */
#line 54 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1566 "otm5UNL.c"
  memset (b_84 + 1913, 48, 2);
  /* initialize field WS-Count-Rows */
#line 55 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1571 "otm5UNL.c"
  memset (b_84 + 1915, 48, 7);
  /* initialize field DB-Schema */
#line 57 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1576 "otm5UNL.c"
  memset (b_84 + 1922, 32, 12);
  /* initialize field DB-UName */
#line 58 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1581 "otm5UNL.c"
  memset (b_84 + 1934, 32, 12);
  /* initialize field DB-UPass */
#line 59 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1586 "otm5UNL.c"
  memset (b_84 + 1946, 32, 12);
  /* initialize field DB-Host */
#line 60 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1591 "otm5UNL.c"
  memset (b_84 + 1958, 32, 32);
  /* initialize field DB-Socket */
#line 61 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1596 "otm5UNL.c"
  memset (b_84 + 1990, 32, 64);
  /* initialize field DB-Port */
#line 62 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1601 "otm5UNL.c"
  memset (b_84 + 2054, 32, 5);
  /* initialize field Main-Record-Move-Flag */
#line 66 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1606 "otm5UNL.c"
  *(cob_u8_ptr)(b_84 + 2059) = 48;
  /* initialize field FA-RDBMS-Flat-Statuses */
#line 72 "../copybooks/wsfnctn.cob"
  cob_nop ();
#line 1611 "otm5UNL.c"
  memset (b_84 + 2060, (unsigned char)'0', 5);

  /* initialize field pre-trans-name */
#line 13 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1617 "otm5UNL.c"
  memcpy (b_155, "pretrans.tmp", 12);
  memset (b_155 + 12, ' ', 520);
  /* initialize field post-trans-name */
#line 14 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1623 "otm5UNL.c"
  memcpy (b_155 + 532, "postrans.tmp", 12);
  memset (b_155 + 532 + 12, ' ', 520);
  /* initialize field file-0 */
#line 1 "../copybooks/file00.cob"
  cob_nop ();
#line 1629 "otm5UNL.c"
  memcpy (b_155 + 1064, "system.dat", 10);
  memset (b_155 + 1064 + 10, ' ', 522);
  /* initialize field file-2 */
#line 1 "../copybooks/file02.cob"
  cob_nop ();
#line 1635 "otm5UNL.c"
  memcpy (b_155 + 1596, "archive.dat", 11);
  memset (b_155 + 1596 + 11, ' ', 521);
  /* initialize field file-3 */
#line 1 "../copybooks/file03.cob"
  cob_nop ();
#line 1641 "otm5UNL.c"
  memcpy (b_155 + 2128, "final.dat", 9);
  memset (b_155 + 2128 + 9, ' ', 523);
  /* initialize field file-4 */
#line 1 "../copybooks/file04.cob"
  cob_nop ();
#line 1647 "otm5UNL.c"
  memcpy (b_155 + 2660, "slautogen.dat", 13);
  memset (b_155 + 2660 + 13, ' ', 519);
  /* initialize field file-5 */
#line 1 "../copybooks/file05.cob"
  cob_nop ();
#line 1653 "otm5UNL.c"
  memcpy (b_155 + 3192, "ledger.dat", 10);
  memset (b_155 + 3192 + 10, ' ', 522);
  /* initialize field file-6 */
#line 1 "../copybooks/file06.cob"
  cob_nop ();
#line 1659 "otm5UNL.c"
  memcpy (b_155 + 3724, "posting.dat", 11);
  memset (b_155 + 3724 + 11, ' ', 521);
  /* initialize field file-7 */
#line 1 "../copybooks/file07.cob"
  cob_nop ();
#line 1665 "otm5UNL.c"
  memcpy (b_155 + 4256, "batch.dat", 9);
  memset (b_155 + 4256 + 9, ' ', 523);
  /* initialize field file-8 */
#line 1 "../copybooks/file08.cob"
  cob_nop ();
#line 1671 "otm5UNL.c"
  memcpy (b_155 + 4788, "postings2irs.dat", 16);
  memset (b_155 + 4788 + 16, ' ', 516);
  /* initialize field file-9 */
#line 1 "../copybooks/file09.cob"
  cob_nop ();
#line 1677 "otm5UNL.c"
  memcpy (b_155 + 5320, "tmp-stock.dat", 13);
  memset (b_155 + 5320 + 13, ' ', 519);
  /* initialize field file-10 */
#line 1 "../copybooks/file10.cob"
  cob_nop ();
#line 1683 "otm5UNL.c"
  memcpy (b_155 + 5852, "staudit.dat", 11);
  memset (b_155 + 5852 + 11, ' ', 521);
  /* initialize field file-11 */
#line 1 "../copybooks/file11.cob"
  cob_nop ();
#line 1689 "otm5UNL.c"
  memcpy (b_155 + 6384, "stockctl.dat", 12);
  memset (b_155 + 6384 + 12, ' ', 520);
  /* initialize field file-12 */
#line 1 "../copybooks/file12.cob"
  cob_nop ();
#line 1695 "otm5UNL.c"
  memcpy (b_155 + 6916, "salesled.dat", 12);
  memset (b_155 + 6916 + 12, ' ', 520);
  /* initialize field file-13 */
#line 1 "../copybooks/file13.cob"
  cob_nop ();
#line 1701 "otm5UNL.c"
  memcpy (b_155 + 7448, "value.dat", 9);
  memset (b_155 + 7448 + 9, ' ', 523);
  /* initialize field file-14 */
#line 1 "../copybooks/file14.cob"
  cob_nop ();
#line 1707 "otm5UNL.c"
  memcpy (b_155 + 7980, "delivery.dat", 12);
  memset (b_155 + 7980 + 12, ' ', 520);
  /* initialize field file-15 */
#line 1 "../copybooks/file15.cob"
  cob_nop ();
#line 1713 "otm5UNL.c"
  memcpy (b_155 + 8512, "analysis.dat", 12);
  memset (b_155 + 8512 + 12, ' ', 520);
  /* initialize field file-16 */
#line 1 "../copybooks/file16.cob"
  cob_nop ();
#line 1719 "otm5UNL.c"
  memcpy (b_155 + 9044, "invoice.dat", 11);
  memset (b_155 + 9044 + 11, ' ', 521);
  /* initialize field file-17 */
#line 1 "../copybooks/file17.cob"
  cob_nop ();
#line 1725 "otm5UNL.c"
  memcpy (b_155 + 9576, "delinvno.dat", 12);
  memset (b_155 + 9576 + 12, ' ', 520);
  /* initialize field file-18 */
#line 1 "../copybooks/file18.cob"
  cob_nop ();
#line 1731 "otm5UNL.c"
  memcpy (b_155 + 10108, "openitm2.dat", 12);
  memset (b_155 + 10108 + 12, ' ', 520);
  /* initialize field file-19 */
#line 1 "../copybooks/file19.cob"
  cob_nop ();
#line 1737 "otm5UNL.c"
  memcpy (b_155 + 10640, "openitm3.dat", 12);
  memset (b_155 + 10640 + 12, ' ', 520);
  /* initialize field file-20 */
#line 1 "../copybooks/file20.cob"
  cob_nop ();
#line 1743 "otm5UNL.c"
  memcpy (b_155 + 11172, "oisort.wrk", 10);
  memset (b_155 + 11172 + 10, ' ', 522);
  /* initialize field file-21 */
#line 1 "../copybooks/file21.cob"
  cob_nop ();
#line 1749 "otm5UNL.c"
  memcpy (b_155 + 11704, "work.tmp", 8);
  memset (b_155 + 11704 + 8, ' ', 524);
  /* initialize field file-22 */
#line 1 "../copybooks/file22.cob"
  cob_nop ();
#line 1755 "otm5UNL.c"
  memcpy (b_155 + 12236, "purchled.dat", 12);
  memset (b_155 + 12236 + 12, ' ', 520);
  /* initialize field file-23 */
#line 1 "../copybooks/file23.cob"
  cob_nop ();
#line 1761 "otm5UNL.c"
  memcpy (b_155 + 12768, "delfolio.dat", 12);
  memset (b_155 + 12768 + 12, ' ', 520);
  /* initialize field file-24 */
#line 1 "../copybooks/file24.cob"
  cob_nop ();
#line 1767 "otm5UNL.c"
  memset (b_155 + 13300, 32, 532);
  /* initialize field file-26 */
#line 1 "../copybooks/file26.cob"
  cob_nop ();
#line 1772 "otm5UNL.c"
  memcpy (b_155 + 13832, "pinvoice.dat", 12);
  memset (b_155 + 13832 + 12, ' ', 520);
  /* initialize field file-27 */
#line 1 "../copybooks/file27.cob"
  cob_nop ();
#line 1778 "otm5UNL.c"
  memcpy (b_155 + 14364, "poisort.wrk", 11);
  memset (b_155 + 14364 + 11, ' ', 521);
  /* initialize field file-28 */
#line 1 "../copybooks/file28.cob"
  cob_nop ();
#line 1784 "otm5UNL.c"
  memcpy (b_155 + 14896, "openitm4.dat", 12);
  memset (b_155 + 14896 + 12, ' ', 520);
  /* initialize field file-29 */
#line 1 "../copybooks/file29.cob"
  cob_nop ();
#line 1790 "otm5UNL.c"
  memcpy (b_155 + 15428, "openitm5.dat", 12);
  memset (b_155 + 15428 + 12, ' ', 520);
  /* initialize field file-30 */
#line 1 "../copybooks/file30.cob"
  cob_nop ();
#line 1796 "otm5UNL.c"
  memcpy (b_155 + 15960, "plautogen.dat", 13);
  memset (b_155 + 15960 + 13, ' ', 519);
  /* initialize field file-31 */
#line 1 "../copybooks/file31.cob"
  cob_nop ();
#line 1802 "otm5UNL.c"
  memcpy (b_155 + 16492, "bostkitm.dat", 12);
  memset (b_155 + 16492 + 12, ' ', 520);
  /* initialize field file-32 */
#line 1 "../copybooks/file32.cob"
  cob_nop ();
#line 1808 "otm5UNL.c"
  memcpy (b_155 + 17024, "pay.dat", 7);
  memset (b_155 + 17024 + 7, ' ', 525);
  /* initialize field file-33 */
#line 1 "../copybooks/file33.cob"
  cob_nop ();
#line 1814 "otm5UNL.c"
  memcpy (b_155 + 17556, "cheque.dat", 10);
  memset (b_155 + 17556 + 10, ' ', 522);
  /* initialize field file-34 */
#line 48 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1820 "otm5UNL.c"
  memcpy (b_155 + 18088, "irsacnts.dat", 12);
  memset (b_155 + 18088 + 12, ' ', 520);
  /* initialize field file-35 */
#line 49 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1826 "otm5UNL.c"
  memcpy (b_155 + 18620, "irsdflt.dat", 11);
  memset (b_155 + 18620 + 11, ' ', 521);
  /* initialize field file-36 */
#line 50 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1832 "otm5UNL.c"
  memcpy (b_155 + 19152, "irspost.dat", 11);
  memset (b_155 + 19152 + 11, ' ', 521);
  /* initialize field file-37 */
#line 51 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1838 "otm5UNL.c"
  memcpy (b_155 + 19684, "irsfinal.dat", 12);
  memset (b_155 + 19684 + 12, ' ', 520);
  /* initialize field file-38 */
#line 52 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1844 "otm5UNL.c"
  memcpy (b_155 + 20216, "postsort.dat", 12);
  memset (b_155 + 20216 + 12, ' ', 520);
  /* initialize field File-Defs-Count */
#line 55 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1850 "otm5UNL.c"
  cob_move ((cob_field *)&c_23, &f_198);
  /* initialize field File-Defs-os-Delimiter */
#line 56 "../copybooks/wsnames.cob"
  cob_nop ();
#line 1855 "otm5UNL.c"
  *(cob_u8_ptr)(b_155 + 20750) = (unsigned char)' ';

  /* initialize field WS-Called */
#line 6 "../copybooks/wscall.cob"
  cob_nop ();
#line 1861 "otm5UNL.c"
  memset (b_200, (unsigned char)' ', 24);
  /* initialize field WS-Term-Code */
#line 9 "../copybooks/wscall.cob"
  cob_nop ();
#line 1866 "otm5UNL.c"
  memset (b_200 + 24, (unsigned char)'0', 3);
  /* initialize field WS-CD-Args */
#line 13 "../copybooks/wscall.cob"
  cob_nop ();
#line 1871 "otm5UNL.c"
  memset (b_200 + 27, (unsigned char)' ', 13);

  /* initialize field SY003 */
#line 145 "otm5UNL.cbl"
  cob_nop ();
#line 1877 "otm5UNL.c"
  memcpy (b_208, "SY003 Problem reading otm5 file =    ", 37);
  /* initialize field SY006 */
#line 146 "otm5UNL.cbl"
  cob_nop ();
#line 1882 "otm5UNL.c"
  memcpy (b_208 + 37, "SYS06 Write error on .seq file", 30);
  /* initialize field SY007 */
#line 147 "otm5UNL.cbl"
  cob_nop ();
#line 1887 "otm5UNL.c"
  memcpy (b_208 + 67, "SY007 Program arguments incorrect: ", 35);
  /* initialize field SY008 */
#line 148 "otm5UNL.cbl"
  cob_nop ();
#line 1892 "otm5UNL.c"
  memcpy (b_208 + 102, "SY008 Note message & Hit return", 31);
  /* initialize field SY009 */
#line 149 "otm5UNL.cbl"
  cob_nop ();
#line 1897 "otm5UNL.c"
  memcpy (b_208 + 133, "SY009 Environment variables not yet set up : ABORTING", 53);

  /* initialize field COB-CRT-STATUS */
#line 151 "otm5UNL.cbl"
  cob_nop ();
#line 1903 "otm5UNL.c"
  memset (b_214, (unsigned char)'0', 4);


  /* File initialization for open-item-file-5 */
  cob_file_malloc (&h_OPEN_ITEM_FILE_5, &k_OPEN_ITEM_FILE_5, 1, 0);
  k_OPEN_ITEM_FILE_5->field = &f_18;
  k_OPEN_ITEM_FILE_5->tf_duplicates = 0;
  k_OPEN_ITEM_FILE_5->offset = 0;
  h_OPEN_ITEM_FILE_5->select_name = (const char *)"open-item-file-5";
  h_OPEN_ITEM_FILE_5->file_status = h_OPEN_ITEM_FILE_5_status;
  memset (h_OPEN_ITEM_FILE_5_status, '0', 2);
  h_OPEN_ITEM_FILE_5->assign = &f_186;
  h_OPEN_ITEM_FILE_5->record = &f_23;
  h_OPEN_ITEM_FILE_5->variable_record = NULL;
  h_OPEN_ITEM_FILE_5->record_min = 113;
  h_OPEN_ITEM_FILE_5->record_max = 113;
  h_OPEN_ITEM_FILE_5->file = NULL;
  h_OPEN_ITEM_FILE_5->organization = 3;
  h_OPEN_ITEM_FILE_5->access_mode = 2;
  h_OPEN_ITEM_FILE_5->lock_mode = 0;
  h_OPEN_ITEM_FILE_5->open_mode = 0;
  h_OPEN_ITEM_FILE_5->flag_optional = 0;
  h_OPEN_ITEM_FILE_5->flag_line_adv = 0;
  h_OPEN_ITEM_FILE_5->flag_select_features = 1;

  /* File initialization for otm5-File-Seq */
  cob_file_malloc (&h_OTM5_FILE_SEQ, NULL, 0, 0);
  h_OTM5_FILE_SEQ->select_name = (const char *)"otm5-File-Seq";
  h_OTM5_FILE_SEQ->file_status = h_OTM5_FILE_SEQ_status;
  memset (h_OTM5_FILE_SEQ_status, '0', 2);
  h_OTM5_FILE_SEQ->assign = (cob_field *)&c_24;
  h_OTM5_FILE_SEQ->record = &f_63;
  h_OTM5_FILE_SEQ->variable_record = NULL;
  h_OTM5_FILE_SEQ->record_min = 113;
  h_OTM5_FILE_SEQ->record_max = 118;
  h_OTM5_FILE_SEQ->file = NULL;
  h_OTM5_FILE_SEQ->organization = 0;
  h_OTM5_FILE_SEQ->access_mode = 1;
  h_OTM5_FILE_SEQ->lock_mode = 0;
  h_OTM5_FILE_SEQ->open_mode = 0;
  h_OTM5_FILE_SEQ->flag_optional = 0;
  h_OTM5_FILE_SEQ->flag_line_adv = 0;
  h_OTM5_FILE_SEQ->flag_select_features = 1;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump open-item-file-5 */
  cob_dump_file ("FD open-item-file-5", h_OPEN_ITEM_FILE_5);
  cob_dump_field_ext ( 1, "OTM5-Record", &f_17, 0, 0);
  cob_dump_field_ext ( 3, "oi5-key", &f_18, 0, 0);
  cob_dump_field_ext ( 5, "oi5-supplier", COB_SET_FLD (f0, 7, b_17, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "oi5-invoice", COB_SET_FLD (f0, 8, b_17 + 7, &a_12), 0, 0);
  cob_dump_field_ext ( 3, "oi5-date", COB_SET_FLD (f0, 4, b_17 + 15, &a_13), 0, 0);
  cob_dump_field_ext ( 3, "FILLER", COB_SET_FLD (f0, 94, b_17 + 19, &a_1), 0, 0);

  /* Dump otm5-File-Seq */
  cob_dump_file ("FD otm5-File-Seq", h_OTM5_FILE_SEQ);
  cob_dump_field_ext ( 0, "otm5-File-Seq Record", &f_63, 0, 0);

  /* Dump WORKING-STORAGE */
  cob_dump_output ("WORKING-STORAGE");
  cob_dump_field_ext (77, "RETURN-CODE", &f_2, 0, 0);
  cob_dump_field_ext (77, "prog-name", &f_64, 0, 0);
  cob_dump_field_ext (77, "z", &f_65, 0, 0);
  cob_dump_field_ext (77, "OS-Delimiter", &f_66, 0, 0);
  cob_dump_field_ext (77, "ACAS_BIN", &f_67, 0, 0);
  cob_dump_field_ext (77, "ACAS_LEDGERS", &f_68, 0, 0);
  cob_dump_field_ext (77, "Arg-Number", &f_69, 0, 0);
  cob_dump_field_ext ( 1, "Arg-Vals", &f_70, 0, 0);
  {
    int i_1;
    int max_1 = 2;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 3, "Arg-Value", COB_SET_FLD (f0, 525, b_70, &a_1), 0, 1, i_1, 525UL);
    }
  }
  cob_dump_field_ext ( 1, "Arg-Test", &f_72, 0, 0);
  cob_dump_field_ext ( 1, "work-fields", COB_SET_FLD (f0, 9, b_73, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "ws-Rec-Cnt-In", &f_74, 0, 0);
  cob_dump_field_ext ( 3, "ws-Rec-Cnt-Out", &f_75, 0, 0);
  cob_dump_field_ext ( 3, "ws-reply", &f_76, 0, 0);
  cob_dump_field_ext ( 1, "SO-Print", &f_77, 0, 0);
  cob_dump_field_ext ( 1, "ACAS-DAL-Common-data", COB_SET_FLD (f0, 8, b_78, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "SW-Testing", COB_SET_FLD (f0, 1, b_78, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "SW-Testing-2", COB_SET_FLD (f0, 1, b_78 + 1, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "Log-File-Rec-Written", COB_SET_FLD (f0, 6, b_78 + 2, &a_15), 0, 0);
  cob_dump_field_ext ( 1, "File-Access", COB_SET_FLD (f0, 2065, b_84, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "We-Error", COB_SET_FLD (f0, 3, b_84, &a_16), 0, 0);
  cob_dump_field_ext ( 3, "Rrn", COB_SET_FLD (f0, 4, b_84 + 3, &a_17), 0, 0);
  cob_dump_field_ext ( 3, "fs-reply", &f_87, 0, 0);
  cob_dump_field_ext ( 3, "s1", COB_SET_FLD (f0, 1, b_84 + 9, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Curs", COB_SET_FLD (f0, 4, b_84 + 10, &a_4), 0, 0);
  cob_dump_field_ext ( 3, "Curs2", COB_SET_FLD (f0, 4, b_84 + 14, &a_4), 0, 0);
  cob_dump_field_ext ( 3, "ACAS-Path", &f_97, 0, 0);
  cob_dump_field_ext ( 3, "Path-Work", COB_SET_FLD (f0, 525, b_84 + 543, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "FS-Action", COB_SET_FLD (f0, 22, b_84 + 1068, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Logging-Data", COB_SET_FLD (f0, 832, b_84 + 1090, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "Accept-Reply", COB_SET_FLD (f0, 1, b_84 + 1090, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "File-Key-No", COB_SET_FLD (f0, 1, b_84 + 1091, &a_9), 0, 0);
  cob_dump_field_ext ( 5, "ws-Log-System", &f_103, 0, 0);
  cob_dump_field_ext ( 5, "ws-No-Paragraph", COB_SET_FLD (f0, 3, b_84 + 1093, &a_16), 0, 0);
  cob_dump_field_ext ( 5, "SQL-Err", COB_SET_FLD (f0, 5, b_84 + 1096, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "SQL-Msg", COB_SET_FLD (f0, 512, b_84 + 1101, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "SQL-State", COB_SET_FLD (f0, 5, b_84 + 1613, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-File-Key", COB_SET_FLD (f0, 64, b_84 + 1618, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-Log-Where", COB_SET_FLD (f0, 231, b_84 + 1682, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "WS-Log-File-No", &f_110, 0, 0);
  cob_dump_field_ext ( 5, "WS-Count-Rows", COB_SET_FLD (f0, 7, b_84 + 1915, &a_18), 0, 0);
  cob_dump_field_ext ( 3, "RDB-Data", COB_SET_FLD (f0, 137, b_84 + 1922, &a_5), 0, 0);
  cob_dump_field_ext ( 5, "DB-Schema", COB_SET_FLD (f0, 12, b_84 + 1922, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-UName", COB_SET_FLD (f0, 12, b_84 + 1934, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-UPass", COB_SET_FLD (f0, 12, b_84 + 1946, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Host", COB_SET_FLD (f0, 32, b_84 + 1958, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Socket", COB_SET_FLD (f0, 64, b_84 + 1990, &a_1), 0, 0);
  cob_dump_field_ext ( 5, "DB-Port", COB_SET_FLD (f0, 5, b_84 + 2054, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "Main-Record-Move-Flag", COB_SET_FLD (f0, 1, b_84 + 2059, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "FA-RDBMS-Flat-Statuses", COB_SET_FLD (f0, 2, b_84 + 2060, &a_5), 0, 0);
  cob_dump_field_ext ( 7, "FA-File-System-Used", COB_SET_FLD (f0, 1, b_84 + 2060, &a_9), 0, 0);
  cob_dump_field_ext ( 7, "FA-File-Duplicates-In-Use", COB_SET_FLD (f0, 1, b_84 + 2061, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "File-Function", COB_SET_FLD (f0, 2, b_84 + 2062, &a_3), 0, 0);
  cob_dump_field_ext ( 3, "Access-Type", COB_SET_FLD (f0, 1, b_84 + 2064, &a_9), 0, 0);
  cob_dump_field_ext ( 1, "File-Defs", COB_SET_FLD (f0, 20751, b_155, &a_5), 0, 0);
  cob_dump_field_ext ( 2, "file-defs-a", COB_SET_FLD (f0, 20748, b_155, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "pre-trans-name", COB_SET_FLD (f0, 532, b_155, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "post-trans-name", COB_SET_FLD (f0, 532, b_155 + 532, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-0", COB_SET_FLD (f0, 532, b_155 + 1064, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-2", COB_SET_FLD (f0, 532, b_155 + 1596, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-3", COB_SET_FLD (f0, 532, b_155 + 2128, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-4", COB_SET_FLD (f0, 532, b_155 + 2660, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-5", COB_SET_FLD (f0, 532, b_155 + 3192, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-6", COB_SET_FLD (f0, 532, b_155 + 3724, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-7", COB_SET_FLD (f0, 532, b_155 + 4256, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-8", COB_SET_FLD (f0, 532, b_155 + 4788, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-9", COB_SET_FLD (f0, 532, b_155 + 5320, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-10", COB_SET_FLD (f0, 532, b_155 + 5852, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-11", COB_SET_FLD (f0, 532, b_155 + 6384, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-12", COB_SET_FLD (f0, 532, b_155 + 6916, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-13", COB_SET_FLD (f0, 532, b_155 + 7448, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-14", COB_SET_FLD (f0, 532, b_155 + 7980, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-15", COB_SET_FLD (f0, 532, b_155 + 8512, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-16", COB_SET_FLD (f0, 532, b_155 + 9044, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-17", COB_SET_FLD (f0, 532, b_155 + 9576, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-18", COB_SET_FLD (f0, 532, b_155 + 10108, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-19", COB_SET_FLD (f0, 532, b_155 + 10640, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-20", COB_SET_FLD (f0, 532, b_155 + 11172, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-21", COB_SET_FLD (f0, 532, b_155 + 11704, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-22", COB_SET_FLD (f0, 532, b_155 + 12236, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-23", COB_SET_FLD (f0, 532, b_155 + 12768, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-24", COB_SET_FLD (f0, 532, b_155 + 13300, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-26", COB_SET_FLD (f0, 532, b_155 + 13832, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-27", COB_SET_FLD (f0, 532, b_155 + 14364, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-28", COB_SET_FLD (f0, 532, b_155 + 14896, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-29", &f_186, 0, 0);
  cob_dump_field_ext ( 3, "file-30", COB_SET_FLD (f0, 532, b_155 + 15960, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-31", COB_SET_FLD (f0, 532, b_155 + 16492, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-32", COB_SET_FLD (f0, 532, b_155 + 17024, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-33", COB_SET_FLD (f0, 532, b_155 + 17556, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-34", COB_SET_FLD (f0, 532, b_155 + 18088, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-35", COB_SET_FLD (f0, 532, b_155 + 18620, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-36", COB_SET_FLD (f0, 532, b_155 + 19152, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-37", COB_SET_FLD (f0, 532, b_155 + 19684, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "file-38", COB_SET_FLD (f0, 532, b_155 + 20216, &a_1), 0, 0);
  cob_dump_field_ext ( 2, "File-Defs-Count", &f_198, 0, 0);
  cob_dump_field_ext ( 2, "File-Defs-os-Delimiter", &f_199, 0, 0);
  cob_dump_field_ext ( 1, "WS-Calling-Data", COB_SET_FLD (f0, 40, b_200, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "WS-Called", COB_SET_FLD (f0, 8, b_200, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Caller", COB_SET_FLD (f0, 8, b_200 + 8, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Del-Link", COB_SET_FLD (f0, 8, b_200 + 16, &a_1), 0, 0);
  cob_dump_field_ext ( 3, "WS-Term-Code", COB_SET_FLD (f0, 1, b_200 + 24, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-Process-Func", COB_SET_FLD (f0, 1, b_200 + 25, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-Sub-Function", COB_SET_FLD (f0, 1, b_200 + 26, &a_9), 0, 0);
  cob_dump_field_ext ( 3, "WS-CD-Args", &f_207, 0, 0);
  cob_dump_field_ext ( 1, "Error-Messages", COB_SET_FLD (f0, 186, b_208, &a_5), 0, 0);
  cob_dump_field_ext ( 3, "SY003", &f_209, 0, 0);
  cob_dump_field_ext ( 3, "SY006", &f_210, 0, 0);
  cob_dump_field_ext ( 3, "SY007", &f_211, 0, 0);
  cob_dump_field_ext ( 3, "SY008", &f_212, 0, 0);
  cob_dump_field_ext ( 3, "SY009", &f_213, 0, 0);

  cob_dump_output ("END OF DUMP - otm5UNL");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'otm5UNL' */

/* Initialize module structure for otm5UNL */
static void otm5UNL_module_init (cob_module *module)
{
  module->module_name = "otm5UNL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())otm5UNL;
  module->module_cancel.funcptr = (void *(*)())otm5UNL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

